DB.TXT = {
	
	nomiGiorni:["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],
	nomiMesi:["January","February","March","April","May","June","July","August","September","October","November","December"],

	NoProva: "This function is not available for trial subscriptions",
	// GENERICHE
	Help: "More information",
	Aggiungi: "Add",
	Nuova: "New",
	Nuovo: "New",
	Aggiungi_a: "Add to",
	modifica: "edit",
	Modifica: "Edit",
	Salva: "Save",
	Annulla: "Cancel",
	Invia: "Send",
	Conferma: "Confirm",
	Chiudi: "Close",
	Elimina: "Delete",
	EliminaScheda: "Delete file",
	EliminaCartella: "Delete folder",
	NessunRisultato "No result",
	NoRes "No content",
	UscireSenzaSalvare "Do you really want to exit without saving?",
	SalvataggioInCorso "Saving...",
	OK "OK",
	si "Yes",
	no "No",
	o "or",
	per "For",
	a "To",
	dataNonCorretta "The date jn [d] is not correct",
	SchedaSalvata "The file has been saved",
	InserisciNote "Insert some annotation...",
	SelettoreAnatomia "Anatomy selector",
	// MENU IMPOSTAZIONI
	Impostazioni "Settings",
	Lingua "Language",
	Guide "Show startup tutorial",
	//popup NUOVA VERSIONE	

	NuoveCaratteristiche "New features",
	//popup VERSIONE
	
	Versione "Info about [§]",
	VersioneNumero "Version",
	IdeazioneProgetto "Project",
	SviluppoContenuti "Contents",
	DisegniModellazione "Drawings and 3D modelling",
	ComunicazioneTesting "Marketing and testing",
	VersioneInglese "English version",
	Consulenti "Consultants",
	Collaboratori "Collaborators",
	Ringraziamenti "Special thanks",
	DirittiRiservati "All rights reserved",
	// popup COLORI	
	Colori "Colors and texts",
	ScegliColore "Choose the app color",
	ColoreAmbiente "App color",
	ScegliPelle "Skin type",
	DimTxt "Texts size",
	TxtSML "Small",
	TxtMID "Middle",
	TxtBIG "Big",
	// CARICAMENTO, LOGIN e SINCRONIZZAZIONE
	Caricamento: "Loading...",
	CaricamentoImpostazioni: "Loading settings",
	localdbNotSupp: "We are sorry, your browser is not supported",
	ChiediAnnullaUtente: "Are you sure you want to switch to another user?",
	AttenzioneAnnullaUtente: "CAUTION! If you proceed, all the unsynchronized data saved on this device will be lost.",
	UtenteDisconnesso: "User logged out",
	NessunUtente: "No user logged in",
	NonLoggato: "PLEASE NOTE! You are using the demo version of the app. Click to login.",
	HoCapito: "I understand",
	ContinuaDemo: "Continue with demo",
	Accedi "Login",
	ACCEDI "LOGIN",
	LOGOUT "LOGOUT",
	MsgConnMultipla "WARNING!\nYou're being disconnected because someone else logged in using your and password.\nIf it's not you, we recommend to change it as soon as possible.",
	VuoiLogout "Do you really want to logout?",
	PWDdimenticata "Forgot your login data?",
	ErroreCaricamento "PLEASE NOTE! An error occurred while uploading to the server. The changes you made may not sync with your other devices.",
	ElementoNonSincronizzato "Unsynchronized item. Connect the device to the internet to synchronize.",
	ElementiDaSincronizzare "There are unsynchronized items.",
	ElementiSincronizzati "Items that were changed when you were out of connection were synchronized.",
	MsgLogoutDevices: "The device as been disconnected",
	ErrLogoutDevices: "Si è verificato un errore nel tentativo di disconnettere un dispositivo.",
	MaxDispositiviConnessi: "You can connect up to 2 devices at a time. If you want to connect with this device you have to disconnect one of the connected ones. Choose which one, from the list below.",
	// SCHEDA
	ChiudiScheda "Close file",
	RiapriScheda "RESUME",
	PuntoPrecedente "Previous point",
	PuntoSuccessivo "Next point",
	ElementoGiaAperto "L'elemento che vuoi aprire risulta già aperto su un altro dispositivo. Chiudilo e riprova.",
	// RICERCHE
	GuidaRicerca "Enter keywords and press ENTER (minimum 3 letters)",
	Ricerca "Search",
	Cerca "Search",
	CercaQualcosa "Search something",
	TueRicerche "Your searches",
	SvuotaCronologia "Clear history",
	ConfSvuotaCronologia "Do you really want to clear all search results?",
	EliminaParola "Delete item",
	// MENU SET
	ImpostazioniSet "Set settings",
	ChiudiSet "Leave the map",
	// DISPOSITIVI
	Dispositivi "Connected devices",
	// NOTIFICHE
	Notifiche "Notifications",
	NotificheTorna "Go back to notifications",
	EliminaNotifica "Are you sure you want to delete the notification?",
	NotificheNessuna "No notifications",
	// DOWNLOAD e STAMPA
	Download "Data backup",
	DownloadChiedi "Are you sure you want to download your personal data backup",
	StampaScheda "Print",
	AggancioScheda "Tab hooking",
	StampaStage "Print 3D model",
	StampaRicevuta "Print",
	DownloadScheda "Download",
	PreparazioneStampa "Printing process...",
	BackupsNessuno "No backups",
	CreaBackup "Create your backup",
	NomeBackup "Insert the title of your backup",
	BackupCreato "Your backup has been created",
	EliminaBackup "Are you sure you want to delete the backup?",
	BackupsTorna "Go back to your backups",
	BackupErrore "We're sorry, an error occurred and your backup has not been created.",
	DownloadDati "Download data file",
	RipristinaBackup "Restore this backup",
	BackupRipristinato "Backup restored!",
	EliminaBackup "Delete the backup",
	ChiediEliminaBackup "Are you sure you want to delete the backup from the server?",
	ChiediRipristinaBackup "Are you sure you want to restore your personal data backup. PLEASE NOTE: all data will be deleted. Press NO if you dont want restore this backup.",
	SicuroRipristinaBackup "Are you sure you really want to restore the previous backup? The operation is irreversible and you will lose all current data.",
	maxBackups "You can create a maximum of [n] backups. Delete one to be able to create a new one.",
	Backup "Backup personal data of",
	DataCreazione "Date of creation",
	eOra " and time",
	Tsubo "Tsubo",
	Mezzo "- mezzo -",
	MezzoAgo "Ago",
	MezzoMoxa "Moxa",
	MezzoCoppetta "Coppetta",
	MezzoDiapason "Diapason",
	MezzoLuce "Luce",
	MezzoDito "Dito",
	MezzoPauper "Pauper",
	MezzoSemeVaccaria "Vaccaria seed",
	MezzoSferettaMetallica "Metal ball",
	MezzoElettroAgopuntura "Electro-acupuncture / Electrical detection",
	MezzoAgoSemipermanente "Semi-permanent needle",
	MezzoCrio "Cryo-auriculotherapy",
	MezzoSalasso "Bloodletting",
	MezzoInfiltrazione "Infiltration",
	SpiegazionePuntoTratt "Annotazioni sullo tsubo ...",
	SpiegazioneMeridianoTratt "Annotazioni sul meridiano ...",
	SpiegazioneAuriculoTratt "Annotazioni sullo punto ...",
	AlertMezzoSalasso "Warning! Do not use bloodletting in patients on anticoagulant therapy. This may lead to the risk of uncontrolled bleeding",
	AlertMezzoElettroAgopuntura "Attention!! Do not use electro-acupuncture or electrical detection on patients with a pacemaker. It could lead to the risk of malfunction and death of the patient.",
	ANNOTAZIONI "COMMENTS ON TSUBOS",
	PROCEDURE "CUSTOM PROCEDURES",
	Condiviso "Shared",
	ANNOTAZIONI_GENERICO "COMMENTS ON 3D MODEL",
	m "male",
	f "female",
	a "other",
	TrattamentoSenzaNome "Trattamento senza nome",
	// per il file "verifica_form.js"
	ATTENZIONE "PLEASE NOTE",
	erroreFormatoEmail "The mail format for [1] is not correct...",
	numeriInteri "integer",
	campoNumerici "In the field [1] you must indicate only numbers",
	lunghezzaMinCampo "The length of the field [1] must be minimum [2] letters, now is [3]",
	lunghezzaMaxCampo "The length of the field [1] must be maximum [2] letters, now is [3]",
	inserireValore "You must indicate the [1]",
	selezionareValore "You must indicate the [1]",
	selezionareCasella "You must select the checkbox [1]",
	// CONNESSIONE
	ConnessioneAssente "No active internet connection! this function works only with an internet connection.",
	ErroreUtenteNonConnesso "This operation is not allowed because you are disconnected from the server. Please login and try again.",
	UltimaConnessione "Last connection",
	// FEEDBACK	
	Feedback "Feedback and advices",
	InviaFeedback "Give us a feedback",
	FeedbackInviato "Your feedback has been correctly sent. Thank you for your contribution.",
	FeedbackErrore "We're sorry, an error occurred and your feedback has not been sent. Please try later.",
	ErroreInvio "An error occurred while sending your feedback, try again later.",
	ErroreInvio2 "Send an email to ",
	Oggetto "Subject",
	TestoMessaggio "Message text",
	// BACKUP
	BackupInviato "The backup has been sent to your e-mail address.",
	BackupErrore "We're sorry, an error occurred and your backup has not been sent. Please try later.",
	ErroreLogin "We're sorry, an error occurred with your login. Check carefully if your data are correct.",
	// SERVIZI
	
	NoResServizio "No services",
	ChiediEliminaServizio "Do you really want to delete the service? Please note! It will no longer be recovered.",
	ScegliServizio "Services",
	AggiungiServizio "Add a service",
	ModificaServizio "Service file",
	CreaServizio "New service",
	NomeServizio "Service name",
	DescrizioneServizio "Write a few words to describe the service offered ...",
	CostoServizio "Session cost",
	NumeroSedute "Session number",
	Seduta "Session",
	SedutaSingola "Single session",
	sedute "sessions",
	ErroreNumeroSedute "The number of sessions must be between 1 and 20!",
	AddServiziSpiegazione1 "Select a service or package to add to the customer",
	AddServiziSpiegazione2 "Select or add the folder in which to place the service",
	TornaServizi "Back to services",
	ConfermaAddServizio1 "Vuoi davvero aggiungere il servizio al cliente?",
	ConfermaAddServizio2 "Vuoi davvero aggiungere il servizio composto di [n] sedute al cliente?",
	CopiaDi "Copy of",
	CercaServizio "Search a service...",
	// FORNITORI
	
	NoResFornitore "No supplier",
	ChiediEliminaFornitore "Do you really want to delete the supplier? Please note! It will no longer be recovered.",
	AggiungiFornitore "Add a supplier",
	ModificaFornitore "Supplier file",
	CreaFornitore "New supplier",
	CercaFornitore "Search a supplier...",
	// PAZIENTI
// menu
Pazienti "Your clients",
	NoResPaziente "No client",
	ChiediEliminaPaziente "Do you really want to delete the client? Please note! It will no longer be recovered. Besides every notes referring to the model will be permanently deleted.",
	AggiungiPaziente "Add a client",
	FiltroPazienti "Filters and statistics",
	FiltriApplicati "Filters applied",
	ModificaPaziente "Client file",
	CreaPaziente "New client",
	Anagrafica "Data",
	Nome "Name",
	Cognome "Family name",
	Nominativo "Name",
	Indirizzo "Address",
	CAP "Postal code",
	Citta "Town",
	Provincia "Province",
	Stato "State",
	Telefono "Phone number",
	Cellulare "Mobile number",
	paeseCellulare "Country code",
	Eta "Age",
	Anni "years old",
	Email "Email",
	Sesso "Gender",
	Maschio "Male",
	Femmina "Female",
	Altro "Other",
	DataNascita "Date of birth",
	LuogoNascita "Place of birth",
	Altezza "Height (cm)",
	Peso "Weight (kg)",
	Tags "Tags",
	TagsSpiegazione "Enter a tag ...)",
	
	Medicine "Medicines",
	MedicineSpiegazione "Enter a medicine ...)",
	
	Allergie "Allergies",
	AllergieSpiegazione "Enter an allergy ...)",
	
	Patologie "Pathologies",
	PatologieSpiegazione "Enter a pathology ...)",
	
	Interventi "Surgical interventions",
	InterventiSpiegazione "Enter a surgical intervention ...)",
	
AggiungiTag "Add a tag",
	AggiungiMedicina "Add a medicinal",
	AggiungiAllergia "Add a allergy",
	TagPresente "The tag you want to add already exists. If you haven't added it yet, choose it from the list.",
	MedicinaPresente "The medicinal you want to add already exists. If you haven't added it yet, choose it from the list.",
	AllergiaPresente "The allergy you want to add already exists. If you haven't added it yet, choose it from the list.",
	PatologiaPresente "The pathology you want to add already exists. If you haven't added it yet, choose it from the list.",
	InterventoPresente "The surgery intervention you want to add already exists. If you haven't added it yet, choose it from the list.",
	AggiungiEtichetta "Add a label",
	EtichettaPresente "The label you want to add already exists. If you haven't added it yet, choose it from the list.",
	NoResEtichette "No field found",
	EtichettaSpiegazione "Enter the field label (e.g. sport practiced)",
EtichettaBtn "Add a field",
TipoString "string",
	TipoNumber "numeric",
	TipoDate "date",
	TipoBoolean "true/false",
	Provenienza "Channel",
	Professione "Job",
	Social "Used social",
	RagioneSociale "Company name",
	CodiceFiscale "Fiscal Code",
	PartitaIva "VAT number",
	CaricaImmagine "Upload a pic",
	CancellaImmagine "Delete pic",
	LabelContatti "Contacts",
	LabelFatturazione "Fiscal data",
	LabelStatistiche "Statistics information",
	LabelAggiuntive "Additional information",
	LabelAnnotazioni "Annotations",
	LabelAnagrafici "Personal data",
	LabelBiometrici "Biometric data",
	LabelIndirizzo "Address",
	LabelPrefessione "Job information",
	LabelImpostazioniCommunity "Community settings",
	LabelAnagrafica "Personal information",
	ErrorePrefisso "Devi inserire il prefisso internazionale per il cellulare",
	CercaCliente "Search a client...",
	// TRATTAMENTI
// elenco
Anamnesi "Anamnesis",
	Anamnesi_e_Diagnosi "Anamnesis and diagnosis",
	AggiungiTrattamento "Add a treatment",
	InserisciTrattamento "Insert a treatment in the cycle",
	NoResTrattamento "No treatment",
	TrattamentiSingoli "Single sessions",
	// scheda
ChiediEliminaTrattamento "Do you really want to delete the treatment?",
	ModificaTrattamento "Treatment file",
	CreaTrattamento "New treatment",
	Data "Date",
	Titolo "Title",
	TestoTrattamento "Treatment description ...",
	Note "Notes",
	Etichetta "Label",
	Costo "Price",
	AnamnesiMotivo "Motivo per il quale si prescrive il ciclo ...",
	AnamnesiDiagnosiOccidentale "Western diagnosis",
	AnamnesiDiagnosiMTC "TCM diagnosis",
	Prescrizione "Prescription",
	// tsubo e valutazione
MeridianiTrattamento "Meridians",
	MeridianiAnamnesi "Evaluation on meridians",
	PuntiAuriculo "Auricular points",
	PuntiTrattamento "Treated tsubo",
	PuntiDaTrattare "Tsubo to be treated",
	AggiungiGruppo "Import group",
	AggiungiPunti "Add point",
	AggiungiMeridiani "Import meridiani",
	ImportaPunto "Point",
	ImportaPunti "Import tsubo from...",
	ImportaMeridiani "Import meridiani from...",
	ModificaCon "To edit this section you must open  ",
	PuntiAnamnesi "Evaluation on tsubo",
	PuntiPresenti "Some points were already in, so they haven't been added ",
	MeridianiPresenti "Some meridians were already in, so they haven't been added ",
	AggiungiMeridiano "Meridian",
	AggiungiPunto "Add point",
	SpSuDett "Move up",
	DelDett "Delete",
	PVDett "Energetic evaluation",
	PZDett "Mezzo utilizzato",
	VisualizzaPunto "Show point file",
	ScegliMeridiano "choose a meridian",
	Valutazione "NEUTRAL",
	ValutazioneP "FULL",
	ValutazioneV "EMPTY",
	ValutazioneD "PAIN",
	SelezionaTutti "Select all",
	Importa "IMPORT",
	ErroreImportaPunti "You must select a point",
	// sintomi
AggiungiSintomo "Add a symptom",
	Diagnosi "Diagnosis",
	Sintomi "Symptoms",
	Gallery "Pics",
	ScoresSintomi "Course of symptoms",
	SintomoSpiegazione "Enter a symptom (e.g. stomach ache)",
	
NoResSintomi "No symptom found",
	erroreDuplicazioneElemento "Please note! The item is already in the list.",
Componi "Write a message",
Destinatari "Recipients",
DestinatariTutti "All clients",
DestinatariFiltrati "Filtered clients",

	SpostaTrattamento "Sposta in un'altra cartella",



MsgComponiEmail "You must fill in all fields.",
	
// gallery
AggiungiFoto "Add pic",
	ChiediEliminaFoto "Do you really want to delete the pic?",
	// cartella clinica
	Cartelle "Folders",
	SpostaIn "Move to...",
	CicloTrattamenti "Tratments cycles",
	ModificaCiclo "Edit cycle",
	SchedaAnamnesi "Anamnesis file",
	AggiungiCiclo "New a cycle",
	Ciclo "Cycle name",
	CreaCiclo "New cycle",
	GuidaCicloTit "Cos'è un ciclo di trattamenti",
	GuidaCiclo "Creando un ciclo di trattamenti aggiungerai una cartella nella quale potrai inserire una serie di trattamenti raggruppati secondo uno specifico obiettivo terapeutico (es. Trattamento dell'insonnia)."+chr10+"Nella scheda del ciclo puoi gestire alcuni parametri che non sono presenti nei trattamenti singoli, come ad esempio la diagnosi."+chr10+"I sintomi indicati in questa scheda potranno essere monitorati e aggiornati nel corso di tutto il ciclo di trattamenti e infine potrai visualizzare e stampare la scheda riepoligativa del ciclo completo.",
	CicloTrattamenti "Treatment cycle",
	CicloSenzaNome "Single treatments",
	CicloPresente "This folder name is already in use. You can't duplicate it.",
	ChiediEliminaCiclo "Do you really want to delete the entire folder? N.B. It will no longer be possible to recover it. Furthermore, all the treatments contained therein will also be permanently deleted.",
	SchedaCiclo "Overview",
	// scheda SALDI	
ElSaldi "Payments",
	AncoraSaldare "Not payed",
	AggiungiSaldo "Add a payment",
	MotivoSaldo "Reason of payment",
	RicevutaSaldo "Payment receipt ",
	RicevutaNumero "Receipt nr.",
	ValoreSaldo "Payment amount",
	DataSaldo "Date",
	InserisciSaldo "Add a payment",
	ChiediEliminaSaldo "Do you really want to delete the payment?",
	NoResSaldi "No payment",
	Intestazione "Header",
	IntestazioneSpiegazione "Header of the company...",
	// filtri e statistiche
FasceEta "Age group",
	Generi "Genders",
	Province "Regions",
	Professioni "Jobs",
	Provenienze "Channels",
	Nessuno "Nothing",
	TotalePazienti "Number of clients",
	ApplicaFiltri "Apply filters",
	PazientiFiltrati "Clients filtered",
	StrumentiMarketing "Marketing tools",
	InviaEmailPazienti "Send multiple emails",
	EmailPazienti "Multiple emails",
	ComponiEmailPazienti "Compose the message",
	AnteprimaEmailPazienti "Message preview",
	InviaSmsPazienti "Send multiple sms",
	AnnullaFiltri "Cancel filters",
	ErroreNumeroEmail "None of the filtered clients registered an email address",
	NumeroEmail1 "You are about to send a message to 1 recipient",
	NumeroEmailM "You are about to send a message to [n] recipients",
	ChiediInvioEmail "Do you really want to send the message to everyone?",
	ChiediEliminaEmail "Do you really want to delete the message?",
	EmailInviata "The message was successfully sent to all recipients!",
	EmailEliminata "The message was successfully deleted!",
	EmailSalvata "The message was successfully saved!",
	EmailErrore "We're sorry, an error occurred and your message has not been sent. Please try later.",
	EmailErroreS "We're sorry, an error occurred and your message has not been saved. Please try later.",
	AnteprimaEmail "Preview",
	MarketingSpiegazione "Use marketing tools to send targeted communications to your customers. With the tools below, crossed with the filters, you will be able to send messages to previously selected patients in order to advertise your services or current promotions.",
	DataInvio "Send date",
	AlertCodaGiorno "Delivery times exceeding 1 day",
	AlertCodaOra "Delivery times exceeding 1 hour",
	AlertCodaOre "Delivery times exceeding [n] hours",
	AlertCoda20min "Delivery times over 20 minutes",
	AlertMaxMsgVolta "You can send a maximum of [n] messages at a time",

AlertMaxMsgMese "Your monthly [n] message quota has been exceeded",
	
	
// Generiche backup

		
	Descrizione "Description",
	// AGENDA	
DataProgrammata "Scheduled",
	ScegliData "choose a date",
	FinoAlle "Until ...",
	dalle "from",
	alle "to",
	Agenda "Agenda",
	AggiungiAppuntamento "Add appointment",
	ModificaAppuntamento "Edit appointment",
	EliminaAppuntamento "Delete this appointment",
	ChiediEliminaAppuntamento "Really you want to delete this appointment?",
	AggiungiAppuntamentoDati "on day [d] from [1] to [2]",
	TornaAiClienti "Back to clients",
	AggiungiCartella "Create a cycle and add",
	GenericoAppSpiegazione "Enter here some text ...",
	GenericoAppLabel "Enter here a label for the treatmen...",
	ClientiAppSpiegazione "Select a client or write his name here ...",
	AppuntamentoCliente "Select a client",
	AppuntamentoConverti "Converti in trattamento",
	ChiediConvertire "Vuoi davvero convertire l'appuntamento in un trattamento?",
	AppuntamentoGenerico "Generic appointment",
	ErroreTestoApp "You must enter some text for the appointment",
	// COMMUNITY
Pseudonimo "Nickname",
	NoteCommunity "Please note! Your profile, necessary to share your personal contents in the Community, is not complete yet. Once saved it will no longer be editable.",
	RegoleCommunityTit "Community rules",
	RegoleCommunityTxt "I accept and subscribe the following rules",
	ErrorePseudonimo "Your nickname is already in use",
	TestoRegoleCommunity "- I'm aware that every shared informations, included the nickname used above, could be seen by other Community users<br>- I subscribe not to make visible to other Community users any sensitive data about my clients, particularly the ones related to their health, and I accept full responsibility in case of leak of this kind of informations.",
	/*	ImpostazioniCommunity "Community settings",
	AssensoCommunity "Consent",*/
		
		
// ---------------
	

	
// STATS
SpazioUtilizzato "Used space",
	Elementi "Items stored",
	ElTotale "Total items",
	ElAnnotazioni "Notes on points",
	ElProcedure "Custom procedures",
	ElPazienti "Clients",
	ElFornitori "Suppliers",
	ElServizi "Services",
	ElGestionale "File management",
	ElTrattamenti "Treatments",
	UltimaSincronizzazione "Last synchronization",
	mai "never",
	ScadenzaPassword "Password expiry",
	ScadenzaConnessione "Connection expiry",
	ScadenzaToken "Token expiry",
	// Messaggi benvenuto
MessaggioBenvenuto "[§] is the new platform that allows you to study, work and share your knowledge in the wellness and health sectors.",
	NonVisualizzarePiu "Do not show anymore",
	// GUIDE
	ReferenceGuide 'Reference guide',
		
GuidaGenericaTit 'Discover the app',
	
GuidaGenericaTxt 'Use the menu to navigate all content and functions. In the settings icon [*] you will find all the additional features and tools to log in or register.',
		
GuidaPazientiTxt 'From this menu you can manage your work. Access one of the sections below to view, add and manage personal data and medical records.',
	
	
noVisPiu 'Do not show again',
	
	loginGuida 'Do you already have a license?',
	
// UTENTE
Web 'Web site',
	
Curriculum 'Curriculum',
	
ProvinciaNascita 'Province',
	
DescrizionePersonale 'Personal description',
	
IntestazioneAzienda 'Company header',
	
ModificaUtente 'Edit your data',
	
visDati 'Show your data',
	
visEmail 'Show your email',
	
visScheda 'Show your profile',
	
azienda 'It\'s a company',
	
Registrati 'Sign-up free',
	
TrattamentoDati 'I agree to data treatment',
	
linkPrivacy 'show',
	
TestoRegistrazione 'Sign-up to use all the features of the free version.',
	
	TestoRegistrazioneEspanso 'With the free registration to [§] you will have {30-day free trial of all apps} and upon expiry you will be able to use all the basic functions of the app:'+chr10+chr10+"[#] Up to 20 customers"+chr10+"[#] Data backup"+chr10+"[#] Cross-platform access"+chr10+"[#] Community functionality"+chr10+"[#] Tutte le app gratis per 30 giorni"+chr10+"[#] 10% discount on [IAOMAI] product",
	ErroreGenerico "An error has occurred",
	ErroreEmailDuplicato "The email address is already in use",
	ErroreUsernameDuplicato "The Username is already in use",
	ConfermareRegistrazione "Registration successful. Log in to your email to certify your account and start using [§].",
	ConfermaRegistrazione "Registration successful. Start using [§] immediately!",
	// CONTROLLI VERSIONI
MsgNoAnatomy "With the free version you can only view the anatomical details of bones, heart and pectoral major muscle.",
	MsgMaxPazienti1 "With the free version you can manage only one client. Register for free to manage up to 15 clients or purchase a Clients Full package with unlimited medical files!",
	MsgMaxPazienti15 "With the free registration you can manage up to 15 clients. Purchase a Clients Full package for unlimited medical files!",
	MsgMaxFornitori1 "With the free version you can manage only one supplier. Register for free to manage up to 5 suppliers or purchase a Clients Full package with unlimited files!",
	MsgMaxFornitori5 "With the free registration you can manage up to 5 suppliers. Purchase a Clients Full package for unlimited files!",
	MsgMaxServizi1 "With the free version you can manage only one service. Register for free to manage up to 5 services or purchase a Clients Full package with unlimited files!",
	MsgMaxServizi5 "With the free registration you can manage up to 5 services. Purchase a Clients Full package for unlimited files!",
	MsgMaxProcedure "With the free version you can manage only one procedure. Buy a TsuboMap license to manage unlimited procedures!",
	MsgMaxCicli "With the free version you can manage only one medical file per client. Buy a Clients Full package with unlimited medical files!",
	MsgFunzioneSoloPay "You cannot use this feature with the free version.",
	MsgContSoloPay "You cannot view this content with the free version.",
	MsgModelloSoloPay "With the free version you can only view the male 3D model.",
	ApriAnatomia "Always open the 3D model at the beginning",
	ApriMappa "Memorize your choice",
	Pelle "Show skin",
	Ossa "Show bones, organs and bowels",
	Muscoli "Show muscles",
	Anatomia "Anatomy",
	Anatomia3D "AnatomyMap",
	// LE MAPPE		
	TsuboMap "TsuboMap",
	TsuboMapST "Acupuncture points atlas",
	TsuboMapDESCR "TsuboMap is the set that allows you to study the concepts of Traditional Chinese Medicine applied to acupuncture points (tsubo) and energy meridians. In addition to complete anatomy and patient management, a list of more than 130 preconfigured pathologies and their treatment according to TCM is available to you. You will also be able to develop customized treatment procedures and share them in the Community.",
	ShiatsuMap "ShiatsuMap",
	ShiatsuMapST "Shiatsu Meridians",
	ShiatsuMapDESCR "The set contains the paths of the Shiatsu meridians according to the theory of Shizuto Masunaga and the theoretical information on the elements.",
	ReflessologiaPlantare "ReflexologyMap",
	ReflessologiaPlantareST "Foot Reflexology",
		ReflessologiaPlantareDESCR "Foot reflexology maps and zones according to the Western view.",
	
	AuriculoMap "AuriculoMap",
	AuriculoMapST "Auriculotherapy",
		AuriculoMapDESCR "The set contains the map of points of auricology and the treatment of ailments through auriculotherapy.",
	
	TriggerPoints "TriggerPointsMap",
	TriggerPointsST "Trigger points",
		TriggerPointsDESCR "Map of trigger points and pain reflex zones.",
	
	Anatomy "AnatomyMap",
	AnatomyST "Anatomy and physiology",
		AnatomyDESCR "With AnatomyMap you will have the complete 3D anatomical models that include muscles, bones, organs and viscera. For each anatomical detail you can also consult the descriptive sheet and insert personalized annotations.",
	
	MedicalFiles "Patients management",
	MedicalFilesST "Personal data and medical files",
		MedicalFilesDESCR "Complete management of your patients with medical records, treatments, balances and appointment diary",


		
		
	/*CaricaMappa "Load a set",
	Mappe "Additional sets",*/
	CaricaMappa "Load a map",
	Mappe "Thematic maps",
	ChiediEsciMappa "Do you really want quit [mappa]?",
	
// popup SETS
	/*SetAperto "Set in use",
	ApriSet "Open set",*/
	SetAperto "Map in use",
	ApriSet "Open map",
	ApriDemo "Open demo",
	ComeAttivare "Discover how to activate it",
	ChiediInfo "Ask info",
	SetAcquistato "Set activated",
	PrestoInArrivo "COMING SOON",
	InviaRichiesta "Send request",
	SpiegazioneSetsTit "How to activate an additional set",
		
	SpiegazioneSetsTxt "The additional sets of [§] allow you to enrich the platform for professional use, according to your needs and the disciplines of your interest. All the sets can be subscribed in a multi-platform license, that is, you can use them without time and device limitations (PC, tablet and smartphone), simply by downloading the app or using them in the online version. To activate an additional set you need to purchase a license on [§] website or by compiling the form below.",
		
	DataPubblicazione "Expected publication date",
		
	ErroreNessunSet "You must select at least one set",




	CaricamentoMeridiani "Loading meridian's set",
	CaricamentoMappe "Loading sets",
	Anatomia "Anantomy",
	Modelli "Models",
	Opzioni "Options",
	Selezionati "Selected items",
	ChiudiTutto "Unselect all items",
	
	spegniGuida "Do not show again",
	guida0 "Use the man icon to discover the anatomy of the 3D model",
	guida1 "Browse the contents by opening the menu",
	guida2 "Use the settings menu to customize your app",
	guida3 "Commands for the 3D model",
	
	guida_modello0 "Choose the model you want to view",
	guida_modello1 "Move the slide to control the opacity of each anatomical layer",
	guida_modello2 "Open the list of muscles, bones, organs and bowels",
		
	ModelloDonna "Female model",
	ModelloUomo "Male model",
	ModelloPiede "Select feet model",
	ModelloOrecchio "Select ear model",
	CaricamentoModelloDonna "Loading anatomical model",
	CaricamentoModelloUomo "Loading anatomical model",
	CaricamentoModelloPiede "Loading anatomical model",
	CaricamentoModelloOrecchio "Loading anatomical model",
	ApriScheda "Open file",
	CentraDaQui "Center from here",
	Deseleziona "Deselect",
	DeselezionaAltri "Deselect others",
	Isola "Isolate",
	/*CercaMuscoli "Filter MUSCLES list",*/
		
	CercaMuscoli "Filter list",
	CercaOssa "Filter BONES list",
	CercaVisceri "Filter ORGANS and BOWELS list",
	LivelliPrecar "Choose a 3D anatomical model to view by clicking on one of the icons above.",
	ScaricaModello "Exit from 3D model",
	Pausa3D "Metti in pausa il 3D",
	_3DinPausa "3D in pausa: riavvia",
	CentraModello "Centra il modello",
	ElementiSelezionati "Elementi selezionati",
	MostraPin "Mostra/nascondi pins",
	RiflettiModello "Rifletti il modello",
	ChiediUscitaSet1 "Uscendo dal modello 3D uscirai anche da [NomeSet]. Vuoi procedere comunque?",
	ChiediUscitaSet2 "Selezionando questo modello uscirai da [NomeSet]. Vuoi procedere comunque?",
	DX "RIGHT",
	SX "LEFT",
	Muscolo "Muscle",
	Area "",
	Osso "Bone",
	Organo "Organ",
	// ORGANI E VISCERI
		
	Organo_OCCHI "EYE",
	Organo_POLMONI "LUNG",
	Organo_LINGUA "TONGUE",
	Organo_CUORE "HEART",
	Organo_TIMO "THYMUS",
	Organo_BRONCHI "BRONCHUS",
	Organo_TRACHEA "TRACHEA",
	Organo_TIROIDE "THYROID",
	Organo_LARINGE "LARYNX",
	Organo_ESOFAGO "ESOPHAGUS",
	Organo_STOMACO "STOMACH",
	Organo_INTESTINO_TENUE "SMALL INTESTINE",
	Organo_DUODENO "DUODENUM",
	Organo_INTESTINO_CRASSO "LARGE INTESTINE",
	Organo_COLON_ASCENDENTE "ASCENDING COLON",
	Organo_COLON_DISCENDENTE "DESCENDING COLON",
	Organo_COLON_TRASVERSO "TRANSVERSE COLON",
	Organo_RETTO "RECTUM",
	Organo_ANO "ANUS",
	Organo_APPENDICE "APPENDIX",
	Organo_FEGATO "LIVER",
	Organo_MILZA "SPLEEN",
	Organo_PANCREAS "PANCREAS",
	Organo_VESCICA "BLADDER",
	Organo_CISTIFELLEA "GALL BLADDER",
	Organo_SURRENALI "ADRENAL",
	Organo_RENI "KIDNEY",
	Organo_URETERE "URETER",
	Organo_URETRA "URETHRA",
	Organo_GENITALI "GENITALS",
	Organo_UTERO "UTERUS",
	Organo_VAGINA "VAGINA",
	Organo_TUBE "FALLOPIAN TUBE",
	Organo_OVAIE "OVARY",
	Organo_TESTICOLI "TESTIS",
	Organo_PENE "PENIS",
	Organo_VESCICOLE_SEMINALI "SEMINAL VESCICLE",
	Organo_PROSTATA "PROSTATE GLAND",
	Organo_DOTTI_DEFERENTI "DOCTUS DEFERENS",
	Organo_EPIDIDIMIO "EPIDIDYMIS",
	Organo_MAMMELLE "BREASTS",
	Organo_CERVELLO "BRAIN",
	Organo_MIDOLLO "SPINAL CORD",
	// OSSA
		
	Osso_BACINO "HIP",
	Osso_ILIACO "ILIACUS",
	Osso_CRANIO "SKULL",
	Osso_MANDIBOLA "JAW",
	Osso_OMERO "HUMERUS",
	Osso_CARTILAGINE_PUBICA "SYNPHISIS PUBIS",
	Osso_CARPO "CARPUS",
	Osso_METACARPO "METACARPUS",
	Osso_ASTRAGALO "TALUS",
	Osso_CALCAGNO "CALCANEUS",
	Osso_CARTILAGINI_STERNOCOSTALI "COSTAL CARTILAGES",
	Osso_CLAVICOLA "COLLARBONE",
	Osso_COSTE "RIBS",
	Osso_FEMORE "FEMUR",
	Osso_IOIDE "HYOID BONE",
	Osso_METATARSO "METATARSUS",
	Osso_ATLANTE "ATLAS",
	Osso_EPISTROFEO "AXIS",
	Osso_FALANGI_MANO "PROXIMAL PHALANGES (HAND)",
	Osso_FALANGINE_MANO "INTERMEDIATE PHALANGES (HAND)",
	Osso_FALANGETTE_MANO "DISTAL PHALANGES (HAND)",
	Osso_FALANGI_PIEDE "PROXIMAL PHALANGES (FOOT)",
	Osso_FALANGINE_PIEDE "INTERMEDIATE PHALANGES (FOOT)",
	Osso_FALANGETTE_PIEDE "DISTAL PHALANGES (FOOT)",
	Osso_PERONE "FIBULA",
	Osso_RADIO "RADIUS",
	Osso_ROTULA "PATELLA",
	Osso_SACRO_E_COCCIGE "SACRUM AND COCCYX",
	Osso_SACRO "SACRUM",
	Osso_COCCIGE "COCCYX",
	Osso_SCAPOLE "SHOULDER BONE",
	Osso_STERNO "STERNUM",
	Osso_TARSO "TARSUS",
	Osso_TIBIA "TIBIA",
	Osso_ULNA "ULNA",
	Osso_VERTEBRE_CERVICALI "CERVICAL VERTEBRAE",
	Osso_VERTEBRE_DORSALI "THORACIC VERTEBRAE",
	Osso_VERTEBRE_LOMBARI "LUMBAR VERTEBRAE",
	Osso_DISCHI_INTERVERTEBRALI "INTERVERTEBRAL DISCS",
	Osso_ALLUCE_FALANGE_1 "PROXIMAL PHALANGE OF BIG TOE",
	Osso_ALLUCE_FALANGE_2 "DISTAL PHALANGE OF BIG TOE",
	Osso_CUBOIDE "CUBOID",
	Osso_CUNEIFORME_1 "MEDIAL CUNEIFORM",
	Osso_CUNEIFORME_2 "INTERMEDIATE CUNEIFORM",
	Osso_CUNEIFORME_3 "LATERAL CUNEIFORM",
	Osso_DITO_2_F1 "PROXIMAL PHALANGE OF 2° TOE",
	Osso_DITO_2_F2 "INTERMEDIATE PHALANGE OF 2° TOE",
	Osso_DITO_2_F3 "DISTAL PHALANGE OF 2° TOE",
	Osso_DITO_3_F1 "PROXIMAL PHALANGE OF 3° TOE",
	Osso_DITO_3_F2 "INTERMEDIATE PHALANGE OF 3° TOE",
	Osso_DITO_3_F3 "DISTAL PHALANGE OF 3° TOE",
	Osso_DITO_4_F1 "PROXIMAL PHALANGE OF 4° TOE",
	Osso_DITO_4_F2 "INTERMEDIATE PHALANGE OF 4° TOE",
	Osso_DITO_4_F3 "DISTAL PHALANGE OF 4° TOE",
	Osso_DITO_5_F1 "PROXIMAL PHALANGE OF 5° TOE",
	Osso_DITO_5_F2 "INTERMEDIATE PHALANGE OF 5° TOE",
	Osso_DITO_5_F3 "TDISTAL PHALANGE OF 4° TOE",
	Osso_METATARSO_1 "1° METATARSAL",
	Osso_METATARSO_2 "2° METATARSAL",
	Osso_METATARSO_3 "3° METATARSAL",
	Osso_METATARSO_4 "4° METATARSAL",
	Osso_METATARSO_5 "5° METATARSAL",
	Osso_SCAFOIDE "NAVICULAR",
	Osso_CARTILAGINE_AURICOLARE "Cartilage",
	Muscolo_GRAN_DORSALE "LATISSIMUS DORSI",
	Muscolo_RETTO_DELL_ADDOME "RECTUS ABDOMINIS",
	Muscolo_OBLIQUO_ESTERNO_ADDOME "ABDOMINAL EXTERNAL OBLIQUE",
	Muscolo_OBLIQUO_INTERNO_ADDOME "ABDOMINAL INTERNAL OBLIQUE",
	Muscolo_DENTATO_ANTERIORE "SERRATUS ANTERIOR",
	Muscolo_PETTORALE "PECTORAL MAJOR",
	Muscolo_INFRASPINATO "INFRASPINATUS",
	Muscolo_GRANDE_ROTONDO "TERES MAJOR",
	Muscolo_PICCOLO_ROTONDO "TERES MINOR",
	Muscolo_GRANDE_GLUTEO "GLUTEUS MAXIMUS",
	Muscolo_TENSORE_DELLA_FASCIA_LATA "TENSOR FASCIAE LATAE",
	Muscolo_MEDIO_GLUTEO "GLUTEUS MEDIUS",
	Muscolo_TRAPEZIO "TRAPEZIUS",
	Muscolo_FRONTALE "FRONTALIS",
	Muscolo_OCCIPITALE "OCCIPITALIS",
	Muscolo_ORBICOLARE_DELL_OCCHIO "ORBICULARIS OCULI",
	Muscolo_TEMPORALE "TEMPOROPARIETALIS",
	Muscolo_MASSETERE "MASSETER",
	Muscolo_PROCERO "PROCERUS",
	Muscolo_ZIGOMATICO "ZYGOMATICUS",
	Muscolo_ELEVATORE_DEL_LABBRO "LEVATOR LABII SUPERIORIS",
	Muscolo_DEPRESSORE_ANGOLO_BOCCA "DEPRESSOR ANGULI ORIS",
	Muscolo_ELEVATORE_ALA_NASO "LEVATOR LABII SUP. ALAEQUE NASI",
	Muscolo_CORRUGATORE "CORRUGATOR SUPERCILII",
	Muscolo_BUCCINATORE "BUCCINATOR",
	Muscolo_PLATISMA "PLATYSMA",
	Muscolo_RISORIO "RISORIUS",
	Muscolo_DEPRESSORE_LABBRO "DEPRESSOR LABII INFERIORIS",
	Muscolo_ORBICOLARE_BOCCA "ORBICULARIS ORIS",
	Muscolo_NASALE "NASALIS",
	Muscolo_MENTALE "MENTALIS",
	Muscolo_MILOIOIDEO "MYLOHYOID",
	Muscolo_STILOIOIDEO "STYLOHYOID",
	Muscolo_DIGASTRICO "DIGASTRIC",
	Muscolo_STERNOCLEIDOMASTOIDEO "STERNOCLEIDOMASTOID",
	Muscolo_STERNOIOIDEO "STERNOHYOID",
	Muscolo_OMOIOIDEO "OMOHYOID",
	Muscolo_TIROIDEO "THYROHYOID",
	Muscolo_SCALENI "SCALENE MUSCLES",
	Muscolo_SPLENIO_DELLA_TESTA "SPLENIUS CAPITIS",
	Muscolo_ELEVATORE_DELLA_SCAPOLA "LEVATOR SCAPULAE",
	Muscolo_SARTORIO "SARTORIUS",
	Muscolo_QUADRICIPITE_FEMORALE "QUADRICEPS FEMORIS",
	Muscolo_VASTO_LATERALE "VASTUS LATERALIS",
	Muscolo_VASTO_MEDIALE "VASTUS MEDIALIS",
	Muscolo_RETTO "RECTUS FEMORIS",
	Muscolo_GRACILE "GRACILIS",
	Muscolo_ADDUTTORE_LUNGO "ADDUCTOR LONGUS",
	Muscolo_PETTINEO "PECTINEUS",
	Muscolo_ILEO "ILIACUS",
	Muscolo_GRANDE_PSOAS "PSOAS MAJOR",
	Muscolo_BICIPITE_FEMORALE "BICEPS FEMORIS",
	Muscolo_SEMITENDINOSO "SEMITENDINOSUS",
	Muscolo_SEMIMEMBRANOSO "SEMIMEMBRANOSUS",
	Muscolo_GRANDE_ADDUTTORE "ADDUCTOR MAGNUS",
	Muscolo_DELTOIDE "DELTOID",
	Muscolo_CORACOBRACHIALE "CORACOBRACHIALIS",
	Muscolo_BICIPITE_BRACHIALE "BICEPS BRACHII",
	Muscolo_TRICIPITE_BRACHIALE "TRICEPS BRACHII",
	Muscolo_BRACHIALE "BRACHIALIS",
	Muscolo_ANCONEO "ANCONEUS",
	Muscolo_BRACHIORADIALE "BRACHIORADIALIS",
	Muscolo_ESTENSORE_RADIALE_LUNGO_CARPO "EXTENSOR CARPI RADIALIS LONGUS",
	Muscolo_ESTENSORE_RADIALE_BREVE_CARPO "EXTENSOR CARPI RADIALIS BREVIS",
	Muscolo_ABDUTTORE_LUNGO_POLLICE "ABDUCTOR POLLICIS LONGUS",
	Muscolo_ESTENSORE_BREVE_POLLICE "EXTENSOR POLLICIS BREVIS",
	Muscolo_ESTENSORE_LUNGO_POLLICE "EXTENSOR POLLICIS LONGUS",
	Muscolo_ESTENSORE_COMUNE_DITA "EXTENSOR DIGITORUM",
	Muscolo_ESTENSORE_PROPRIO_MIGNOLO "EXTENSOR DIGITI MINIMI",
	Muscolo_ESTENSORE_ULNARE_CARPO "EXTENSOR CARPI ULNARIS",
	Muscolo_FLESSORE_ULNARE_CARPO "FLEXOR CARPI ULNARIS",
	Muscolo_PRONATORE "PRONATOR TERES",
	Muscolo_FLESSORE_RADIALE_CARPO "FLEXOR CARPI RADIALIS",
	Muscolo_PALMARE_LUNGO "PALMARIS LONGUS",
	Muscolo_FLESSORI_SUPERFICIALI_DITA "FLEXOR DIRIGORUM SUPERFICIALIS",
	Muscolo_ABDUTTORE_BREVE_POLLICE "ABDUCTOR POLLICIS BREVIS",
	Muscolo_FLESSORE_BREVE_POLLICE "FLEXOR POLLICIS BREVIS",
	Muscolo_OPPONENTE_POLLICE "OPPONENS POLLICIS",
	Muscolo_ADDUTTORE_POLLICE "ADDUTTOR POLLICIS",
	Muscolo_LOMBRICALI "LUMBRICAL",
	Muscolo_FLESSORE_MIGNOLO_MANO "FLEXOR DIGITI MINIMI BREVIS",
	Muscolo_ABDUTTORE_MIGNOLO_MANO "ABDUCTOR DIGITI MINIMI",
	Muscolo_PALMARE_BREVE "PALMARIS BREVIS",
	Muscolo_INTEROSSEI_DORSALI_MANO "DORSAL INTEROSSEI",
	Muscolo_GASTROCNEMIO "GASTROCNEMIUS",
	Muscolo_TENDINE_ACHILLE "ACHILLES TENDON",
	Muscolo_SOLEO "SOLEUS",
	Muscolo_PERONEO_LUNGO "PERONEUS LONGUS",
	Muscolo_PERONEO_BREVE "PERONEUS BREVIS",
	Muscolo_TIBIALE_ANTERIORE "TIBIALIS ANTERIOR",
	Muscolo_ESTENSORE_LUNGO_DITA "EXTENSOR DIGITORUM LONGUS",
	Muscolo_ESTENSORE_LUNGO_ALLUCE "EXTENSOR HALLUCIS LONGUS",
	Muscolo_ESTENSORE_BREVE_ALLUCE "EXTENSOR HALLUCIS BREVIS",
	Muscolo_ESTENSORI_BREVI_DITA "EXTENSOR DIGITORUM BREVIS",
	Muscolo_ADDUTTORE_ALLUCE "ABDUCTOR HALLUCIS",
	Muscolo_FLESSORE_BREVE_DITA "FLEXOR DIGITORUM BREVIS",
	Muscolo_FLESSORE_LUNGO_DITA "FLEXOR DIGITORUM LONGUS",
	Muscolo_FLESSORE_LUNGO_ALLUCE "FLEXOR HALLUCIS LONGUS",
	Muscolo_ABDUTTORE_MIGNOLO_PIEDE "ABDUTTORE DEL MIGNOLO (PIEDE)",
	Muscolo_FLESSORE_MIGNOLO_PIEDE "FLEXOR DIGITI MINIMI",
	// zone anatomiche
	Zona_TESTA "Head's muscles",
	Zona_ORECCHIO "Ear's areas",
	Zona_COLLO "Neck's muscles",
	Zona_TORSO "Torso's muscles",
	Zona_ARTO_SUPERIORE "Upper limb's muscles",
	Zona_ARTO_INFERIORE "Lower limb's muscles",
	// aree orecchio
	Muscolo_TUBERCOLO_DI_DARWIN "",
	Muscolo_CODA_DELL_ELICE "",
	Muscolo_CORPO_DELL_ELICE "",
	Muscolo_BRANCA_MONTANTE_DELL_ELICE "",
	Muscolo_GINOCCHIO_DELL_ELICE "",
	Muscolo_RADICE_DELL_ELICE "",
	Muscolo_DOCCIA_SCAFOIDE "",
	Muscolo_CRESTA_DELL_AURICOLA "",
	Muscolo_FOSSETTA_TRIANGOLARE "",
	Muscolo_EMICONCA_SUPERIORE "",
	Muscolo_EMICONCA_INFERIORE "",
	Muscolo_TRAGO "",
	Muscolo_ANTITRAGO "",
	Muscolo_ANGOLO_ELICO_LOBULARE "",
	Muscolo_LOBO "",
	Muscolo_SOLCO_PRELOBULARE "",
	Muscolo_SOLCO_SOTTO_ANTITRAGALE "",
	Muscolo_FORO_ACUSTICO_ESTERNO "",
	Muscolo_EMINENZA_LOBOLARE "",
	Muscolo_FOSSA_RETROLOBULARE "",
	Muscolo_CONVESSITA_EMICONCA_INFERIORE "",
	Muscolo_CONVESSITA_EMICONCA_SUPERIORE "",
	Muscolo_EMINENZA_ELICALE "",
	Muscolo_CONVESSITA_FOSSETTA_TRIANGOLARE "",
	Muscolo_DOCCIATURA_ANTELICALE_POSTERIORE "",
	Muscolo_EMINENZA_CENTRALE "",
	Muscolo_FOSSETTA_CENTRALE_POSTERIORE "",
	Muscolo_ANTELICE "",
	Muscolo_RAMO_INFERIORE "",
	Muscolo_RAMO_SUPERIORE "",
}
	