DB.TXT = {
	nomiGiorni:["Domenica","Lunedì","Martedì","Mercoledì","Giovedì","Venerdì","Sabato"],
	nomiMesi:["Gennaio","Febbraio","Marzo","Aprile","Maggio","Giugno","Luglio","Agosto","Settembre","Ottobre","Novembre","Dicembre"],
	
	NoProva: "Questa funzione non è disponibile per gli abbonamenti in prova",
	Help: "Maggiori informazioni",
	Aggiungi: "Aggiungi",
	Nuova: "Nuova",
	Nuovo: "Nuovo",
	Aggiungi_a: "Aggiungi a",
	modifica: "modifica",
	Modifica: "Modifica",	
	Salva: "Salva",
	Annulla: "Annulla",
	Invia: "Invia",
	Conferma: "Conferma",
	Chiudi: "Chiudi",
	Elimina: "Elimina",
	EliminaScheda: "Elimina la scheda",	
	EliminaCartella: "Elimina la cartella",
	NessunRisultato: "Nessun risultato",
	NoRes: "Nessun contenuto",
	UscireSenzaSalvare: "Vuoi davvero uscire dalle modifiche senza salvare?",
	SalvataggioInCorso: "Salvataggio in corso...",
	OK: "OK",
	si: "Sì",
	no: "No",
	o: "o",
	per: "Per",
	a: "A",
	dataNonCorretta: "La data inserita in [d] non è corretta.",
	SchedaSalvata: "La scheda è stata salvata.",
	InserisciNote: "Inserisci qualche nota...",
	SelettoreAnatomia: "Selettore anatomia",

	// MENU IMPOSTAZIONI
	Impostazioni: "Impostazioni",
	Lingua: "Lingua",
	Guide: "Visualizza la guida iniziale",

	//popup NUOVA VERSIONE
	NuoveCaratteristiche: "Nuove caratteristiche",

	//popup VERSIONE
	Versione: "Info su [§]",
	VersioneNumero: "Versione",
	IdeazioneProgetto: "Ideazione e progetto",
	SviluppoContenuti: "Sviluppo contenuti",
	DisegniModellazione: "Disegni e modellazione 3D",
	ComunicazioneTesting: "Comunicazione e testing",
	VersioneInglese: "Versione inglese",
	Consulenti: "Consulenti",
	Collaboratori: "Collaboratori",
	Ringraziamenti: "Ringraziamenti",
	DirittiRiservati: "Tutti i diritti riservati",
	
	// popup COLORI	
	Colori: "Colori e testi",
	ScegliColore: "Scegli il colore dell'app",
	ColoreAmbiente: "Colore dell'app",
	ScegliPelle: "Tipo di pelle",
	DimTxt: "Dimensione testi",
	TxtSML: "Piccolo",
	TxtMID: "Medio",
	TxtBIG: "Grande",
	
	// CARICAMENTO, LOGIN e SINCRONIZZAZIONE
	Caricamento: "Caricamento...",
	CaricamentoImpostazioni: "Caricamento delle impostazioni...",
	localdbNotSupp: "Siamo spiacenti, il browser che stai usando non è supportato",
	ChiediAnnullaUtente: "Vuoi davvero cambiare utente?",
	AttenzioneAnnullaUtente: "ATTENZIONE! Procedendo, verranno persi tutti i dati salvati su questo dispositivo e non ancora sincronizzati.",
	UtenteDisconnesso: "Utente disconnesso",
	NessunUtente: "Nessun utente connesso",
	NonLoggato: "ATTENZIONE! Stai utilizzando la versione demo dell'app. Clicca per effettuare il login.",
	HoCapito: "Ho capito",
	ContinuaDemo: "Continua con la demo",
	Accedi: "Accedi",
	ACCEDI: "ACCEDI",
	LOGOUT: "LOGOUT",
	MsgConnMultipla: "ATTENZIONE!\nSei stato disconnesso perché qualcun altro è entrato sul sistema con la tua password.\nSe non sei stato tu ti consigliamo di modificarla al più presto.",
	VuoiLogout: "Vuoi davvero disconnetterti?",
	PWDdimenticata: "Hai dimenticato i dati di accesso?",
	ErroreCaricamento: "ATTENZIONE! Si e' verificato un errore nel caricamento sul server. Le modifiche che hai effettuato potrebbero non essere sincronizzate con gli altri dispositivi.",
	ElementoNonSincronizzato: "Elemento non sincronizzato. Connetti il dispositivo a internet per sincronizzare.",
	ElementiDaSincronizzare: "Sono presenti elementi non sincronizzati.",
	ElementiSincronizzati: "Sono stati sincronizzati gli elementi modificati quando eri in assenza di connessione.",
	MsgLogoutDevices: "Il dispositivo è stato disconnesso",
	ErrLogoutDevices: "Si è verificato un errore nel tentativo di disconnettere un dispositivo.",
	MaxDispositiviConnessi: "Puoi connettere un massimo di 2 dispositivi per volta. Se vuoi connetterti con questo dispositivo devi disconnetterne uno di quelli connessi. Scegli quale, dall'elenco qui sotto.",
	
	// SCHEDA
	ChiudiScheda: "Chiudi la scheda",
	RiapriScheda: "RIAPRI",
	PuntoPrecedente: "Vai al punto precedente",
	PuntoSuccessivo: "Vai al punto successivo",
	ElementoGiaAperto: "L'elemento che vuoi aprire risulta già aperto su un altro dispositivo. Chiudilo e riprova.",

	// RICERCHE
	GuidaRicerca: "Inserisci i termini da ricercare e premi il tasto INVIO (minimo 3 lettere)",
	Ricerca: "Ricerca",
	Cerca: "Cerca",
	CercaQualcosa: "Cerca qualcosa",
	TueRicerche: "Le tue ricerche",
	SvuotaCronologia: "Svuota cronologia",
	ConfSvuotaCronologia: "Vuoi davvero cancellare tutti i risultati di ricerca?",
	EliminaParola: "Elimina l'elemento",

	// MENU SET
	ImpostazioniSet: "Impostazioni del set",
	ChiudiSet: "Esci dalla mappa",

	// DISPOSITIVI
	Dispositivi: "Dispositivi connessi",
		
	// NOTIFICHE
	Notifiche: "Notifiche",
	NotificheTorna: "Torna alle notifiche",
	EliminaNotifica: "Vuoi davvero eliminare la notifica?",
	NotificheNessuna: "Nessuna notifica",

	// DOWNLOAD e STAMPA
	Download: "Backup dei dati",
	DownloadChiedi: "Vuoi davvero scaricare il backup dei tuoi dati",
	StampaScheda: "Stampa la scheda",
	AggancioScheda: "Aggancio scheda",
	StampaStage: "Stampa il manichino",
	StampaRicevuta: "Stampa la ricevuta",
	DownloadScheda: "Scarica la scheda",
	PreparazioneStampa: "Preparazione della stampa...",
	BackupsNessuno: "Nessun backup",
	CreaBackup: "Crea un backup",
	NomeBackup: "Inserisci un nome per il backup",
	BackupCreato: "Il backup è stato creato con successo",
	EliminaBackup: "Vuoi davvero eliminare il backup?",
	BackupsTorna: "Torna ai tuoi backups",
	BackupErrore: "Si è verificato un errore nella creazione del backup",
	DownloadDati: "Scarica scheda dati",
	RipristinaBackup: "Ripristina questo backup",
	BackupRipristinato: "Backup ripristinato con successo!",
	EliminaBackup: "Elimina il backup",
	ChiediEliminaBackup: "Vuoi davvero eliminare il backup dal server?",
	ChiediRipristinaBackup: "Vuoi davvero ripristinare il backup selezionato? N.B. tutti i dati attuali verranno sostituiti. Se non vuoi davvero sostituire i dati attuali con quelli del backup premi NO",
	SicuroRipristinaBackup: "Sei sicuro di voler davvero ripristinare il backup precedente? L'operazione è irreversibile e perderai tutti i dati attuali.",
	maxBackups: "Puoi creare un massimo di [n] backups. Cancellane uno per poterne creare uno nuovo.",
	Backup: "Backup dati personali di",
	DataCreazione: "Data di creazione",
	eOra: " e ora",
	Tsubo: "Tsubo",
	Mezzo: "- mezzo -",
	MezzoAgo: "Ago",
	MezzoMoxa: "Moxa",
	MezzoCoppetta: "Coppetta",
	MezzoDiapason: "Diapason",
	MezzoLuce: "Luce",
	MezzoDito: "Dito",
	MezzoPauper: "Pauper",
	MezzoSemeVaccaria: "Seme di Vaccaria",
	MezzoSferettaMetallica: "Sferetta metallica",
	MezzoElettroAgopuntura: "Elettro-agopuntura / Detezione elettrica",
	MezzoAgoSemipermanente: "Ago semipermanente",
	MezzoCrio: "Crio-auricoloterapia",
	MezzoSalasso: "Microsalasso",
	MezzoInfiltrazione: "Infiltrazione",
	SpiegazionePuntoTratt: "Annotazioni sullo tsubo ...",	
	SpiegazioneMeridianoTratt: "Annotazioni sul meridiano ...",	
	SpiegazioneAuriculoTratt: "Annotazioni sullo punto ...",
	AlertMezzoSalasso: "Attenzione!! Non utilizzare il salasso in pazienti sotto terapia anticoagulante. Potrebbe comportare rischio di sanguinamento incontrollato.",
	AlertMezzoElettroAgopuntura: "Attenzione!! Non utilizzare l'elettro-agopuntura o la detezione elettrica su pazienti sui quali è stato innestato un pacemaker. Potrebbe comportare rischio di malfunzionamento e morte del paziente.",
	ANNOTAZIONI: "ANNOTAZIONI SUGLI TSUBO",
	PROCEDURE: "PROCEDURE PERSONALIZZATE",
	Condiviso: "Condiviso",
	ANNOTAZIONI_GENERICO: "ANNOTAZIONI SUL MANICHINO GENERICO",
	m: "maschio",
	f: "femmina",
	a: "altro",
	TrattamentoSenzaNome: "Trattamento senza nome",

	// per il file "verifica_form.js"
	ATTENZIONE: "ATTENZIONE",
	erroreFormatoEmail: "Il formato dell'email per il campo [1] non è esatto...",
	numeriInteri: "interi",
	campoNumerici: "Nel campo [1] puoi inserire solo valori numerici",
	lunghezzaMinCampo: "Il campo [1] deve contenere minimo [2] caratteri, attualmente ne contiene [3]",
	lunghezzaMaxCampo: "Il campo [1] deve contenere massimo [2] caratteri, attualmente ne contiene [3]",
	inserireValore: "Devi inserire un valore per il campo [1]",
	selezionareValore: "Devi selezionare un valore per il campo [1]",
	selezionareCasella: "Devi selezionare la casella [1]",

	// CONNESSIONE
	ConnessioneAssente: "Connessione assente! Per questa funzione è necessaria la connessione a internet.",
	ErroreUtenteNonConnesso: "Questa operazione non è consentita perché sei disconnesso dal server. Effettua il login e riprova.",
	UltimaConnessione: "Ultima connessione",

	// FEEDBACK	
	Feedback: "Feedback, consigli e segnalazioni",
	InviaFeedback: "Invia un feedback",
	FeedbackInviato: "Feedback inviato correttamente. Ti ringraziamo per il tuo contributo.",
	FeedbackErrore: "Si è verificato un errore nell'invio del tuo Feedback. Ti preghiamo di riprovare più tardi.",
	ErroreInvio: "Si è verificato un errore nell'invio del feedback, riprova più tardi.",
	ErroreInvio2: "In alternativa puoi scrivere un email a ",
	Oggetto: "Oggetto",
	TestoMessaggio: "Testo del messaggio",

	// BACKUP
	BackupInviato: "Il backup è stato inviato alla tua casella di posta elettronica.",
	BackupErrore: "Si è verificato un errore nell'invio del backup. Ti preghiamo di riprovare più tardi.",
	ErroreLogin: "Si è verificato un errore nell'autenticazione. Verifica di aver inserito tutti i tuoi dati corretti.",
		
	// SERVIZI
	NoResServizio: "Nessun servizio",
	ChiediEliminaServizio: "Vuoi davvero eliminare il servizio? N.B. Non sarà più possibile recuperarlo.",
	ScegliServizio: "Servizi",
	AggiungiServizio: "Aggiungi un servizio",
	ModificaServizio: "Scheda servizio",
	CreaServizio: "Nuovo servizio",
	NomeServizio: "Nome del servizio",
	DescrizioneServizio: "Scrivi qualche parola per descrivere il servizio offerto ...",
	CostoServizio: "Costo seduta",
	NumeroSedute: "Numero sedute",
	Seduta: "Seduta",
	SedutaSingola: "Seduta singola",
	sedute: "sedute",
	ErroreNumeroSedute: "Il numero di sedute deve essere compreso tra 1 e 20!",
	AddServiziSpiegazione1: "Seleziona un servizio o un pacchetto da aggiungere al cliente",
	AddServiziSpiegazione2: "Seleziona o aggiungi la cartella in cui inserire il servizio",
	TornaServizi: "Torna ai servizi",
	ConfermaAddServizio1: "Vuoi davvero aggiungere il servizio al cliente?",
	ConfermaAddServizio2: "Vuoi davvero aggiungere il servizio composto di [n] sedute al cliente?",
	CopiaDi: "Copia di",
	CercaServizio: "Cerca un servizio...",
		
	// FORNITORI
	NoResFornitore: "Nessun fornitore",
	ChiediEliminaFornitore: "Vuoi davvero eliminare il fornitore? N.B. Non sarà più possibile recuperarlo.",
	AggiungiFornitore: "Aggiungi un fornitore",
	ModificaFornitore: "Anagrafica fornitore",
	CreaFornitore: "Nuovo fornitore",
	CercaFornitore: "Cerca un fornitore...",
		
	// PAZIENTI
	// menu
	Pazienti: "I tuoi clienti",
	NoResPaziente: "Nessun cliente",
	ChiediEliminaPaziente: "Vuoi davvero eliminare il cliente? N.B. Non sarà più possibile recuperarlo. Inoltre verranno cancellate definitivamente anche tutte le note associate al manichino.",
	AggiungiPaziente: "Aggiungi un cliente",
	FiltroPazienti: "Filtri e statistiche",
	FiltriApplicati: "Filtri applicati",
	ModificaPaziente: "Anagrafica cliente",
	CreaPaziente: "Nuovo cliente",
	Anagrafica: "Anagrafica",
	Nome: "Nome",
	Cognome: "Cognome",
	Nominativo: "Nominativo",
	Indirizzo: "Indirizzo",
	CAP: "CAP",
	Citta: "Città",
	Provincia: "Provincia",
	Stato: "Stato",
	Telefono: "Telefono",
	Cellulare: "Cellulare",
	paeseCellulare: "Prefisso paese",
	Eta: "Età",
	Anni: "anni",
	Email: "Email",
	Sesso: "Genere",
	Maschio: "Maschio",
	Femmina: "Femmina",
	Altro: "Altro",
	DataNascita: "Data di nascita",
	LuogoNascita: "Luogo di nascita",
	Altezza: "Altezza (cm)",
	Peso: "Peso (kg)",
	Tags: "Tags",
	TagsSpiegazione: "Inserisci un tag ...",
	Medicine: "Medicinali",
	MedicineSpiegazione: "Inserisci una medicina ...",
	Allergie: "Allergie",
	AllergieSpiegazione: "Inserisci un'allergia ...",
	Patologie: "Patologie",
	PatologieSpiegazione: "Inserisci una patologia ...",
	Interventi: "Interventi chirurgici",
	InterventiSpiegazione: "Inserisci un intervento chirurgico ...",
	AggiungiTag: "Aggiungi tag",
	AggiungiMedicina: "Aggiungi medicinale",
	AggiungiAllergia: "Aggiungi allergia",
	TagPresente: "Il tag che vuoi aggiungere esiste già. Se non l'hai ancora aggiunto sceglilo dall'elenco.",
	MedicinaPresente: "Il medicinale che vuoi aggiungere esiste già. Se non l'hai ancora aggiunta sceglila dall'elenco.",
	AllergiaPresente: "L'allergia che vuoi aggiungere esiste già. Se non l'hai ancora aggiunta sceglila dall'elenco.",
	PatologiaPresente: "La patologia che vuoi aggiungere esiste già. Se non l'hai ancora aggiunta sceglila dall'elenco.",
	InterventoPresente: "L'intervento chirurgico che vuoi aggiungere esiste già. Se non l'hai ancora aggiunta sceglila dall'elenco.",
	AggiungiEtichetta: "Aggiungi un'etichetta",
	EtichettaPresente: "L'etichetta che vuoi aggiungere esiste già. Se non l'hai ancora aggiunta sceglila dall'elenco.",
	NoResEtichette: "Nessun campo presente",
	EtichettaSpiegazione: "Inserisci l'etichetta del campo (es. sport praticato)",
	EtichettaBtn: "Aggiungi un campo",
	TipoString: "testuale",
	TipoNumber: "numerico",	
	TipoDate: "data",
	TipoBoolean: "vero/falso",	
	Provenienza: "Canale",
	Professione: "Professione",
	Social: "Social usato",
	RagioneSociale: "Ragione sociale",
	CodiceFiscale: "Codice Fiscale",
	PartitaIva: "PartitaIva",
	CaricaImmagine: "Carica un'immagine",
	CancellaImmagine: "Cancella l'immagine",
	LabelContatti: "Contatti",
	LabelFatturazione: "Dati fiscali",
	LabelStatistiche: "Informazioni statistiche",
	LabelAggiuntive: "Informazioni aggiuntive",
	LabelAnnotazioni: "Annotazioni",
	LabelAnagrafici: "Dati anagrafici",
	LabelBiometrici: "Dati biometrici",
	LabelIndirizzo: "Indirizzo",
	LabelPrefessione: "Informazioni professionali",
	LabelImpostazioniCommunity: "Impostazioni della community",
	LabelAnagrafica: "Informazioni anagrafiche",
	ErrorePrefisso: "Devi inserire il prefisso internazionale per il cellulare",
	CercaCliente: "Cerca un cliente...",
		
	// TRATTAMENTI
	// elenco
	Anamnesi: "Anamnesi",
	Anamnesi_e_Diagnosi: "Anamnesi e diagnosi",
	AggiungiTrattamento: "Aggiungi un trattamento",
	InserisciTrattamento: "Inserisci un trattamento nel ciclo",
	NoResTrattamento: "Nessun trattamento",
	TrattamentiSingoli: "Sessioni singole",

	// scheda
	ChiediEliminaTrattamento: "Vuoi davvero eliminare il trattamento?",
	ModificaTrattamento: "Trattamento",
	CreaTrattamento: "Nuovo trattamento",
	Data: "Data",
	Titolo: "Titolo",
	TestoTrattamento: "Descrizione del trattamento ...",
	Note: "Note",
	Etichetta: "Etichetta",
	Costo: "Costo",
	AnamnesiMotivo: "Motivo per il quale si prescrive il ciclo ...",
	AnamnesiDiagnosiOccidentale: "Diagnosi occidentale",
	AnamnesiDiagnosiMTC: "Diagnosi MTC",
	Prescrizione: "Prescrizione",

	// tsubo e valutazione
	MeridianiTrattamento: "Meridiani",
	MeridianiAnamnesi: "Valutazione sui meridiani",
	PuntiAuriculo: "Punti auricolari",
	PuntiTrattamento: "Tsubo trattati",
	PuntiDaTrattare: "Tsubo da trattare",
	AggiungiGruppo: "Importa gruppo",
	AggiungiPunti: "Aggiungi punto",
	AggiungiMeridiani: "Importa meridiani",
	ImportaPunto: "Punto",
	ImportaPunti: "Importa tsubo da...",
	ImportaMeridiani: "Importa meridiani da...",
	ModificaCon: "N.B: Per modificare questo sezione devi aprire ",
	PuntiAnamnesi: "Valutazione sugli tsubo",
	PuntiPresenti: "Alcuni punti risultano già presenti, quindi non sono stati aggiunti",
	MeridianiPresenti: "Alcuni meridiani risultano già presenti, quindi non sono stati aggiunti",
	AggiungiMeridiano: "Meridiano",
	AggiungiPunto: "Aggiungi punto",
	SpSuDett: "Sposta su",
	DelDett: "Elimina",
	PVDett: "Valutazione energetica",
	PZDett: "Mezzo utilizzato",
	VisualizzaPunto: "Visualizza la scheda del punto",
	ScegliMeridiano: "scegli un meridiano",
	Valutazione: "NEUTRO",
	ValutazioneP: "PIENO",
	ValutazioneV: "VUOTO",
	ValutazioneD: "DOLORE",
	SelezionaTutti: "Seleziona tutti",
	Importa: "IMPORTA",
	ErroreImportaPunti: "Devi selezionare almeno un punto",
		
	// sintomi
	AggiungiSintomo: "Aggiungi sintomo",
	Diagnosi: "Diagnosi",
	Sintomi: "Sintomi",
	Gallery: "Fotografie",
	ScoresSintomi: "Andamento dei sintomi",
	SintomoSpiegazione: "Inserisci un sintomo (es. mal di pancia)",
	NoResSintomi: "Nessun sintomo presente",
	erroreDuplicazioneElemento: "Attenzione! L'elemento è già presente in elenco.",
	Componi: "Scrivi un messaggio",
	Destinatari: "Destinatari",
	DestinatariTutti: "Tutti i clienti",
	DestinatariFiltrati: "Clienti filtrati",
	SpostaTrattamento: "Sposta in un'altra cartella",
	MsgComponiEmail: "Devi compilare tutti i campi.",
		
	// gallery
	AggiungiFoto: "Aggiungi foto",
	ChiediEliminaFoto: "Vuoi davvero eliminare la foto?",
		
	// cartella clinica
	Cartelle: "Cartelle",
	SpostaIn: "Sposta in...",
	CicloTrattamenti: "Ciclo di trattamenti",
	ModificaCiclo: "Modifica ciclo",
	SchedaAnamnesi: "Scheda di anamnesi",
	AggiungiCiclo: "Aggiungi un ciclo",
	Ciclo: "Nome ciclo",
	CreaCiclo: "Nuovo ciclo",
	GuidaCicloTit: "Cos'è un ciclo di trattamenti",
	GuidaCiclo: "Creando un ciclo di trattamenti aggiungerai una cartella nella quale potrai inserire una serie di trattamenti raggruppati secondo uno specifico obiettivo terapeutico (es. Trattamento dell'insonnia)."+chr10+"Nella scheda del ciclo puoi gestire alcuni parametri che non sono presenti nei trattamenti singoli, come ad esempio la diagnosi."+chr10+"I sintomi indicati in questa scheda potranno essere monitorati e aggiornati nel corso di tutto il ciclo di trattamenti e infine potrai visualizzare e stampare la scheda riepoligativa del ciclo completo.",
	CicloTrattamenti: "Ciclo di trattamenti",
	CicloSenzaNome: "Trattamenti singoli",
	CicloPresente: "Il nome della cartella è già stato utilizzato. Non è possibile duplicarlo.",
	ChiediEliminaCiclo: "Vuoi davvero eliminare l'intera cartella? N.B. Non sarà più possibile recuperarla. Inoltre verranno cancellati definitivamente anche tutti i trattamenti contenuti in essa.",
	SchedaCiclo: "Riepilogo",
		
	// scheda SALDI	
	ElSaldi: "Incassi",
	AncoraSaldare: "Ancora da incassare",
	AggiungiSaldo: "Aggiungi un incasso",
	MotivoSaldo: "Motivo dell'incasso",
	RicevutaSaldo: "Ricevuta di incasso",
	RicevutaNumero: "N° ricevuta",
	ValoreSaldo: "Valore dell'incasso",
	DataSaldo: "Data",
	InserisciSaldo: "Inserisci un incasso",
	ChiediEliminaSaldo: "Vuoi davvero eliminare l'incasso?",
	NoResSaldi: "Nessun incasso",
	Intestazione: "Intestazione",
	IntestazioneSpiegazione: "Intestazione dell'azienda ...",

	// filtri e statistiche
	FasceEta: "Fasce di età",
	Generi: "Generi",
	Province: "Province",
	Professioni: "Professioni",
	Provenienze: "Canali",
	Nessuno: "Nessuno",
	TotalePazienti: "Totale clienti",
	ApplicaFiltri: "Applica filtri",
	PazientiFiltrati: "Clienti filtrati",
	StrumentiMarketing: "Strumenti di marketing",
	InviaEmailPazienti: "Invia email multiple",
	EmailPazienti: "Email multiple",
	ComponiEmailPazienti: "Componi il messaggio",
	AnteprimaEmailPazienti: "Anteprima del messaggio",
	InviaSmsPazienti: "Invia sms multipli",
	AnnullaFiltri: "Annulla i filtri",
	ErroreNumeroEmail: "Nessuno dei clienti filtrati ha registrato un indirizzo email",
	NumeroEmail1: "Stai per inviare un messaggio a 1 destinatario",
	NumeroEmailM: "Stai per inviare un messaggio a [n] destinatari",
	ChiediInvioEmail: "Vuoi davvero inviare il messaggio a tutti?",
	ChiediEliminaEmail: "Vuoi davvero eliminare il messaggio?",
	EmailInviata: "Il messaggio è stato correttamente inviato a tutti i destinatari!",
	EmailEliminata: "Il messaggio è stato correttamente eliminato!",
	EmailSalvata: "Il messaggio è stato correttamente salvato!",
	EmailErrore: "Si è verificato un errore nell'invio del messaggio. Ti preghiamo di riprovare più tardi.",
	EmailErroreS: "Si è verificato un errore nel salvataggio del messaggio. Ti preghiamo di riprovare più tardi.",
	AnteprimaEmail: "Anteprima",
	MarketingSpiegazione: "Utilizza gli strumenti di marketing per inviare comunicazioni mirate ai tuoi clienti. Con gli strumenti qui sotto, incrociati con i filtri, sarai in grado di inviare messaggi a pazienti precedentemente selezionati con il fine di pubblicizzare i tuoi servizi o le promozioni del momento.",
	DataInvio: "Data invio",
	AlertCodaGiorno: "Tempi di consegna superiori a 1 giorno",
	AlertCodaOra: "Tempi di consegna superiori a 1 ora",
	AlertCodaOre: "Tempi di consegna superiori a [n] ore",
	AlertCoda20min: "Tempi di consegna superiori a 20 minuti",
	AlertMaxMsgVolta: "Puoi inviare un massimo di [n] messaggi per volta",
	AlertMaxMsgMese: "La tua quota mensile di [n] messaggi è stata superata",

	// Generiche backup
	Descrizione: "Descrizione",

	// AGENDA	
	DataProgrammata: "Programmato",
	ScegliData: "scegli una data",
	FinoAlle: "Fino alle ...",
	dalle: "dalle",
	alle: "alle",
	Agenda: "Agenda",
	AggiungiAppuntamento: "Aggiungi appuntamento",
	ModificaAppuntamento: "Modifica appuntamento",
	EliminaAppuntamento: "Elimina questo appuntamento",
	ChiediEliminaAppuntamento: "Vuoi davvero eliminare questo appuntamento?",
	AggiungiAppuntamentoDati: "il giorno [g] dalle ore [1] alle ore [2]",
	TornaAiClienti: "Torna ai clienti",
	AggiungiCartella: "Crea un ciclo e aggiungi",
	GenericoAppSpiegazione: "Inserisci un testo qui ...",
	GenericoAppLabel: "Inserisci un'etichetta per il trattamento ...",
	ClientiAppSpiegazione: "Seleziona un cliente o scrivi qui il suo nome ...",
	AppuntamentoCliente: "Scegli un cliente",
	AppuntamentoConverti: "Converti in trattamento",
	ChiediConvertire: "Vuoi davvero convertire l'appuntamento in un trattamento?",
	AppuntamentoGenerico: "Appuntamento generico",
	ErroreTestoApp: "Devi inserire un testo per l'appuntamento",
		
	// COMMUNITY
	Pseudonimo: "Pseudonimo",
	NoteCommunity: "Attenzione! Non hai ancora completato il tuo profilo, necessario per condividere i tuoi contenuti nella Community. Una volta memorizzato non sarà più possibile modificarlo",
	RegoleCommunityTit: "Regole della Community",
	RegoleCommunityTxt: "Dichiaro di conoscere e sottoscrivere le seguenti regole",
	ErrorePseudonimo: "Lo pseudonimo scelto è già utilizzato da un altro utente",
	TestoRegoleCommunity: "- Sono a conoscenza che tutte le informazioni condivise ivi compreso lo pseudonimo sopra indicato saranno visibili dagli altri utenti della Community<br>- Mi impegno a non divulgare agli altri utenti della Community dati sensibili relativi ai miei clienti, in particolare quelli relativi al loro stato di salute, e mi assumo ogni responsabilit&agrave; riguardo a eventuali fuoriuscite di informazioni.",
	/*ImpostazioniCommunity: "Impostazioni Community",
	AssensoCommunity: "Assenso",*/

	// STATS
	SpazioUtilizzato: "Spazio utilizzato",
	Elementi: "Elementi in memoria",
	ElTotale: "Totale",
	ElAnnotazioni: "Annotazioni sui punti",
	ElProcedure: "Procedure personalizzate",
	ElPazienti: "Clienti",
	ElFornitori: "Fornitori",
	ElServizi: "Servizi",
	ElGestionale: "Gestione archivi",
	ElTrattamenti: "Trattamenti",
	UltimaSincronizzazione: "Ultima sincronizzazione",
	mai: "mai",
	ScadenzaPassword: "Scadenza password",
	ScadenzaConnessione: "Scadenza connessione",
	ScadenzaToken: "Scadenza token",

	// Messaggi benvenuto
	MessaggioBenvenuto: "[§] è la nuova piattaforma che ti consente di studiare, lavorare e condividere le tue conoscenze nel settore della salute e del benessere.",
	NonVisualizzarePiu: "Non mostrare più",
	
	// GUIDE
	ReferenceGuide: 'Guida in linea',
	GuidaGenericaTit: 'Scopri cosa puoi fare',
	GuidaGenericaTxt: 'Utilizza il menu per navigare tutti i contenuti e le funzioni. Nell\'icona delle impostazioni [*] trovi tutte le funzionalità aggiuntive e gli strumenti per effettuare l\'accesso o registrarti.',
	GuidaPazientiTxt: 'Da questo menu puoi gestire il tuo lavoro. Accedi ad una delle sezioni qui sotto per visualizzare, aggiungere e gestire le anagrafiche e le cartelle cliniche.',
	noVisPiu: 'Non visualizzare più',
	loginGuida: 'Hai già una licenza?',
		
	// UTENTE
	Web: 'Sito web',
	Curriculum: 'Curriculum',
	ProvinciaNascita: 'Provincia',
	DescrizionePersonale: 'Descrizione personale',
	IntestazioneAzienda: 'Intestazione azienda',
	ModificaUtente: 'Modifica i tuoi dati',
	visDati: 'Mostra i tuoi dati',
	visEmail: 'Mostra la tua email',
	visScheda: 'Mostra la tua scheda',
	azienda: "E' un'azienda",
	Registrati: "Registrati gratuitamente",
	TrattamentoDati: "Acconsento al trattamento dei dati",
	linkPrivacy: "visualizza",
	TestoRegistrazione: "Effettua la registrazione per usufruire di tutte le funzionalità della versione gratuita.",
	TestoRegistrazioneEspanso: "Con la registrazione gratuita a [§] avrai {30 giorni di prova gratuita di tutte le app} e allo scadere potrai usufruire di  di tutte le funzionalità di base dell'app:"+chr10+chr10+"[#] Fino a 20 clienti"+chr10+"[#] Backup dei dati"+chr10+"[#] Accesso multipiattaforma"+chr10+"[#] Funzionalità della community"+chr10+"[#] 10% di sconto su un prodotto [IAOMAI]",
	ErroreGenerico: "Si è verificato un errore",
	ErroreEmailDuplicato: "L'indirizzo Email scelto è già utilizzato da un altro utente",
	ErroreUsernameDuplicato: "La Username scelta è già utilizzata da un altro utente",
	ConfermareRegistrazione: "Registrazione avvenuta correttamente. Accedi alla tua posta elettronica per cerificare il tuo account e iniziare ad utilizzare [§].",
	ConfermaRegistrazione: "Registrazione avvenuta correttamente. Inizia da subito ad utilizzare [§]!",
		
	// CONTROLLI VERSIONI
	MsgNoAnatomy: "Con la versione gratuita è possibile visualizzare solo i dettagli anatomici Ossa, cuore e muscolo pettorale.",
	MsgMaxPazienti1: "Con la versione gratuita puoi gestire un solo cliente. Registrati gratuitamente per gestire fino a 15 pazienti o acquista un pacchetto Clients Full con cartelle cliniche illimitate!.",
	MsgMaxPazienti15: "Con la registrazione gratuita puoi gestire fino a 15 clienti. Acquista un pacchetto Clients Full per cartelle cliniche illimitate!.",
	MsgMaxFornitori1: "Con la versione gratuita puoi gestire un solo fornitore. Registrati gratuitamente per gestire fino a 5 fornitori o acquista un pacchetto Clients Full con archivi illimitati!.",
	MsgMaxFornitori5: "Con la registrazione gratuita puoi gestire fino a 5 fornitori. Acquista un pacchetto Clients Full per archivi illimitati!.",
	MsgMaxServizi1: "Con la versione gratuita puoi gestire un solo servizio. Registrati gratuitamente per gestire fino a 5 servizi o acquista un pacchetto Clients Full con archivi illimitati!.",
	MsgMaxServizi5: "Con la registrazione gratuita puoi gestire fino a 5 servizi. Acquista un pacchetto Clients Full per archivi illimitati!.",
	MsgMaxProcedure: "Con la versione gratuita puoi gestire una sola procedura. Acquista una licenza di TsuboMap per gestire procedure illimitate!.",
	MsgMaxCicli: "Con la versione gratuita puoi gestire una sola cartella clinica per cliente. Acquista un pacchetto Clients Full con cartelle cliniche illimitate!.",
	MsgFunzioneSoloPay: "Con la versione gratuita non è possibile utilizzare questa funzione.",
	MsgContSoloPay: "Con la versione gratuita non è possibile visualizzare questo contenuto.",
	MsgModelloSoloPay: "Con la versione gratuita è possibile visualizzare solo il manichino maschile.",
	ApriAnatomia: "Apri sempre il modello 3D all'inizio",
	ApriMappa: "Memorizza la scelta",
	
	// ANATOMIA
	Pelle: "Visualizza la pelle",
	Ossa: "Visualizza ossa, organi e visceri",
	Muscoli: "Visualizza la muscolatura",
	Anatomia: "Anatomia",	
	Anatomia3D: "AnatomyMap",	

	// LE MAPPE		
	TsuboMap: "TsuboMap",	
	TsuboMapST: "Atlante dei punti agopuntura",	
	TsuboMapDESCR: "TsuboMap è il set che ti consente di studiare i concetti della Medicina Tradizionale Cinese applicati ai punti agopuntura (gli tsubo) e i meridiani energetici. Oltre all'anatomia completa e la gestione dei pazienti, è a tua disposizione un elenco di più di 130 patologie preconfigurate e il relativo trattamento secondo la MTC. Potrai inoltre elaborare procedure di trattamento personalizzate e condividerle nella Community."+chr10+chr10+"Il set include anche:"+chr10+"[anatomy_full]",
	ShiatsuMap: "ShiatsuMap",
	ShiatsuMapST: "Meridiani Shiatsu",
	ShiatsuMapDESCR: "Il set contiene i percorsi dei meridiani Shiatsu secondo la teoria di Shizuto Masunaga e le informazioni teoriche sugli elementi."+chr10+chr10+"Il set include anche:"+chr10+"[anatomy_full]",
	ReflessologiaPlantare: "ReflexologyMap",
	ReflessologiaPlantareST: "Reflessologia Plantare",
	ReflessologiaPlantareDESCR: "Mappe e zone della reflessologia del piede secondo la visione occidentale."+chr10+chr10+"Il set include anche:"+chr10+"[anatomy_full]",
	AuriculoMap: "AuriculoMap",
	AuriculoMapST: "Auricologia",
	AuriculoMapDESCR: "Il set contiene la mappa dei punti dell'auricologia e il trattamento dei disturbi attraverso l'auricoloterapia."+chr10+chr10+"Il set include anche:"+chr10+"[anatomy_full]",
	TriggerPoints: "TriggerPointsMap",
	TriggerPointsST: "Trigger points",
	TriggerPointsDESCR: "Mappa dei punti trigger e delle zone riflesse del dolore."+chr10+chr10+"Il set include anche:"+chr10+"[anatomy_full]",
	Anatomy: "AnatomyMap",
	AnatomyST: "Anatomia e fisiologia",
	AnatomyDESCR: "Con AnatomyMap avrai i modelli anatomici 3D completi che includono muscoli, ossa, organi e visceri. Per ogni dettaglio anatomico potrai inoltre consultare la scheda descrittiva e inserire annotazioni personalizzate.",
	MedicalFiles: "Gestione pazienti",
	MedicalFilesST: "Anagrafiche e cartelle cliniche",
	MedicalFilesDESCR: "Gestione completa dei tuoi pazienti con cartelle cliniche, trattamenti, saldi e agenda appuntamenti",
	/*CaricaMappa: "Carica un set",
	Mappe: "Set aggiuntivi",*/
	CaricaMappa: "Carica una mappa",
	Mappe: "Mappe tematiche",
	ChiediEsciMappa: "Vuoi davvero uscire da [mappa]?",
	
	// popup SETS
	/*SetAperto: "Set in uso",	
	ApriSet: "Apri il set",*/
	SetAperto: "Mappa in uso",	
	ApriSet: "Apri la mappa",
	ApriDemo: "Apri demo",
	ComeAttivare: "Scopri come attivarlo",
	ChiediInfo: "Chiedi info",
	SetAcquistato: "Set attivato",
	PrestoInArrivo: "PRESTO IN ARRIVO",
	InviaRichiesta: "Invia la richiesta",	
	SpiegazioneSetsTit: "Come attivare un set aggiuntivo",	
	SpiegazioneSetsTxt: "I set aggiuntivi di [§] ti consentono di arricchire la piattaforma per un uso professionale, a seconda delle tue necessità e le discipline di tuo interesse. Tutti i set sono sottoscrivibili in licenza multipiattaforma, ovvero, potrai usarli senza limitazioni di tempo e di dispositivo (PC, tablet e smartphone), semplicemente scaricando l'app oppure utilizzandoli nella versione online. Per attivare un set aggiuntivo è necessario acquistare una licenza accedendo sito web di [§] oppure compilando il form qui sotto.",
	DataPubblicazione: "Data di pubblicazione prevista",
	ErroreNessunSet: "Devi selezionare almeno un set",
	CaricamentoMeridiani: "Caricamento set di meridiani",
	CaricamentoMappe: "Caricamento sets",
	Anatomia: "Anatomia",
	Modelli: "Modelli",
	Opzioni: "Opzioni",
	Selezionati: "Elementi selezionati",
	ChiudiTutto: "Deseleziona tutti",
	spegniGuida: "Non mostrare più",
	guida0: "Utilizza l'icona dell'omino per scoprire l'anatomia del modello",
	guida1: "Naviga i contenuti aprendo il menu",
	guida2: "Usa il menu impostazioni per personalizzare la tua app",
	guida3: "Comandi per il manichino",
	guida_modello0: "Scegli il modello che vuoi visualizzare",
	guida_modello1: "Sposta lo slide per controllare l'opacità di ogni livello anatomico",
	guida_modello2: "Apri l'elenco di muscoli, ossa, organi e visceri",
	ModelloDonna: "Modello donna",
	ModelloUomo: "Modello uomo",
	ModelloPiede: "modello piedi",
	ModelloOrecchio: "Modello orecchio",
	CaricamentoModelloDonna: "Caricamento modello anatomico",
	CaricamentoModelloUomo: "Caricamento modello anatomico",
	CaricamentoModelloPiede: "Caricamento modello anatomico",
	CaricamentoModelloOrecchio: "Caricamento modello anatomico",
	ApriScheda: "Apri la scheda",
	CentraDaQui: "Centra da qui",
	Deseleziona: "Deseleziona",
	DeselezionaAltri: "Deseleziona gli altri",
	Isola: "Isola",
	/*CercaMuscoli: "Filtra l'elenco MUSCOLI",*/
	CercaMuscoli: "Filtra l'elenco",	
	CercaOssa: "Filtra l'elenco OSSA",	
	CercaVisceri: "Filtra l'elenco ORGANI e VISCERI",	
	LivelliPrecar: "Scegli un modello anatomico in 3D da visualizzare, cliccando su una delle icone qui sopra.",
	ScaricaModello: "Esci dal modello 3D",
	Pausa3D: "Metti in pausa il 3D",
	_3DinPausa: "3D in pausa: riavvia",	
	CentraModello: "Centra il modello",	
	ElementiSelezionati: "Elementi selezionati",
	MostraPin: "Mostra/nascondi pins",	
	RiflettiModello: "Rifletti il modello",
	ChiediUscitaSet1: "Uscendo dal modello 3D uscirai anche da [NomeSet]. Vuoi procedere comunque?",
	ChiediUscitaSet2: "Selezionando questo modello uscirai da [NomeSet]. Vuoi procedere comunque?",

	// PARTI ANATOMICHE
	DX: "DESTRA",
	SX: "SINISTRA",
	Muscolo: "Muscolo",
	Area: "",
	Osso: "Osso",
	Organo: "Organo",

	// ORGANI E VISCERI
	Organo_OCCHI: "OCCHIO",
	Organo_POLMONI: "POLMONE",
	Organo_LINGUA: "LINGUA",
	Organo_CUORE: "CUORE",
	Organo_TIMO: "TIMO",
	Organo_BRONCHI: "BRONCHI",
	Organo_TRACHEA: "TRACHEA",
	Organo_TIROIDE: "TIROIDE",
	Organo_LARINGE: "LARINGE",
	Organo_ESOFAGO: "ESOFAGO",
	Organo_STOMACO: "STOMACO",
	Organo_INTESTINO_TENUE: "INTESTINO TENUE",
	Organo_DUODENO: "DUODENO",
	Organo_INTESTINO_CRASSO: "INTESTINO CRASSO",
	Organo_COLON_ASCENDENTE: "COLON ASCENDENTE",
	Organo_COLON_DISCENDENTE: "COLON DISCENDENTE",
	Organo_COLON_TRASVERSO: "COLON TRASVERSO",
	Organo_RETTO: "RETTO",
	Organo_ANO: "ANO",
	Organo_APPENDICE: "APPENDICE",
	Organo_FEGATO: "FEGATO",
	Organo_MILZA: "MILZA",
	Organo_PANCREAS: "PANCREAS",
	Organo_VESCICA: "VESCICA",
	Organo_CISTIFELLEA: "CISTIFELLEA",
	Organo_SURRENALI: "GHIANDOLA SURRENALE",
	Organo_RENI: "RENE",
	Organo_URETERE: "URETERE",
	Organo_URETRA: "URETRA",
	Organo_GENITALI: "GENITALI",
	Organo_UTERO: "UTERO",
	Organo_VAGINA: "VAGINA",
	Organo_TUBE: "TUBA DI FALLOPPIO",
	Organo_OVAIE: "OVAIO",
	Organo_TESTICOLI: "TESTICOLO",
	Organo_PENE: "PENE",
	Organo_VESCICOLE_SEMINALI: "VESCICOLE SEMINALI",
	Organo_PROSTATA: "PROSTATA",
	Organo_DOTTI_DEFERENTI: "DOTTI DEFERENTI",
	Organo_EPIDIDIMIO: "EPIDIDIMIO",
	Organo_MAMMELLE: "MAMMELLA",
	Organo_CERVELLO: "CERVELLO",
	Organo_MIDOLLO: "MIDOLLO SPINALE",

	// OSSA
	Osso_BACINO: "BACINO",
	Osso_ILIACO: "ILIACO",
	Osso_CRANIO: "CRANIO",
	Osso_MANDIBOLA: "MANDIBOLA",
	Osso_OMERO: "OMERO",
	Osso_CARTILAGINE_PUBICA: "SINFISI PUBICA",
	Osso_CARPO: "CARPO",
	Osso_METACARPO: "METACARPO",
	Osso_ASTRAGALO: "ASTRAGALO",
	Osso_CALCAGNO: "CALCAGNO",
	Osso_CARTILAGINI_STERNOCOSTALI: "CARTILAGINI STERNOCOSTALI",
	Osso_CLAVICOLA: "CLAVICOLA",
	Osso_COSTE: "COSTE",
	Osso_FEMORE: "FEMORE",
	Osso_IOIDE: "IOIDE",
	Osso_METATARSO: "METATARSO",
	Osso_ATLANTE: "ATLANTE",
	Osso_EPISTROFEO: "EPISTROFEO",
	Osso_FALANGI_MANO: "FALANGI PROSSIMALI (MANO)",
	Osso_FALANGINE_MANO: "FALANGI MEDIANE (MANO)",
	Osso_FALANGETTE_MANO: "FALANGI DISTALI (MANO)",
	Osso_FALANGI_PIEDE: "FALANGI PROSSIMALI (PIEDE)",
	Osso_FALANGINE_PIEDE: "FALANGI MEDIANE (PIEDE)",
	Osso_FALANGETTE_PIEDE: "FALANGI DISTALI (PIEDE)",
	Osso_PERONE: "PERONE",
	Osso_RADIO: "RADIO",
	Osso_ROTULA: "ROTULA",
	Osso_SACRO_E_COCCIGE: "SACRO E COCCIGE",
	Osso_SACRO: "SACRO",
	Osso_COCCIGE: "COCCIGE",
	Osso_SCAPOLE: "SCAPOLA",
	Osso_STERNO: "STERNO",
	Osso_TARSO: "TARSO",
	Osso_TIBIA: "TIBIA",
	Osso_ULNA: "ULNA",
	Osso_VERTEBRE_CERVICALI: "VERTEBRE CERVICALI",
	Osso_VERTEBRE_DORSALI: "VERTEBRE DORSALI",
	Osso_VERTEBRE_LOMBARI: "VERTEBRE LOMBARI",
	Osso_DISCHI_INTERVERTEBRALI: "DISCHI INTERVERTEBRALI",
	Osso_ALLUCE_FALANGE_1: "FALANGE PROSSIMALE DELL'ALLUCE",
	Osso_ALLUCE_FALANGE_2: "FALANGE DISTALE DELL'ALLUCE",	
	Osso_CUBOIDE: "CUBOIDE",	
	Osso_CUNEIFORME_1: "1° CUNEIFORME",		
	Osso_CUNEIFORME_2: "2° CUNEIFORME",		
	Osso_CUNEIFORME_3: "3° CUNEIFORME",		
	Osso_DITO_2_F1: "PRIMA FALANGE 2° DITO",	
	Osso_DITO_2_F2: "SECONDA FALANGE 2° DITO",	
	Osso_DITO_2_F3: "TERZA FALANGE 2° DITO",		
	Osso_DITO_3_F1: "PRIMA FALANGE 3° DITO",	
	Osso_DITO_3_F2: "SECONDA FALANGE 3° DITO",	
	Osso_DITO_3_F3: "TERZA FALANGE 3° DITO",			
	Osso_DITO_4_F1: "PRIMA FALANGE 4° DITO",	
	Osso_DITO_4_F2: "SECONDA FALANGE 4° DITO",	
	Osso_DITO_4_F3: "TERZA FALANGE 4° DITO",				
	Osso_DITO_5_F1: "PRIMA FALANGE 5° DITO",	
	Osso_DITO_5_F2: "SECONDA FALANGE 5° DITO",	
	Osso_DITO_5_F3: "TERZA FALANGE 5° DITO",		
	Osso_METATARSO_1: "1° METATARSO",		
	Osso_METATARSO_2: "2° METATARSO",		
	Osso_METATARSO_3: "3° METATARSO",		
	Osso_METATARSO_4: "4° METATARSO",		
	Osso_METATARSO_5: "5° METATARSO",			
	Osso_SCAFOIDE: "NAVICOLARE",	
	Osso_CARTILAGINE_AURICOLARE: "Cartilagine",	
	Muscolo_GRAN_DORSALE: "GRAN DORSALE",
	Muscolo_RETTO_DELL_ADDOME: "RETTO DELL'ADDOME",	
	Muscolo_OBLIQUO_ESTERNO_ADDOME: "OBLIQUO ESTERNO DELL'ADDOME",	
	Muscolo_OBLIQUO_INTERNO_ADDOME: "OBLIQUO INTERNO DELL'ADDOME",		
	Muscolo_DENTATO_ANTERIORE: "DENTATO ANTERIORE",	
	Muscolo_PETTORALE: "PETTORALE",	
	Muscolo_INFRASPINATO: "INFRASPINATO",	
	Muscolo_GRANDE_ROTONDO: "GRANDE ROTONDO",	
	Muscolo_PICCOLO_ROTONDO: "PICCOLO ROTONDO",	
	Muscolo_GRANDE_GLUTEO: "GRANDE GLUTEO",	
	Muscolo_TENSORE_DELLA_FASCIA_LATA: "TENSORE DELLA FASCIA LATA",	
	Muscolo_MEDIO_GLUTEO: "MEDIO GLUTEO",	
	Muscolo_TRAPEZIO: "TRAPEZIO",		
	Muscolo_FRONTALE: "FRONTALE",	
	Muscolo_OCCIPITALE: "OCCIPITALE",		
	Muscolo_ORBICOLARE_DELL_OCCHIO: "ORBICOLARE DELL'OCCHIO",		
	Muscolo_TEMPORALE: "TEMPORALE",	
	Muscolo_MASSETERE: "MASSETERE",		
	Muscolo_PROCERO: "PROCERO",		
	Muscolo_ZIGOMATICO: "ZIGOMATICO",		
	Muscolo_ELEVATORE_DEL_LABBRO: "ELEVATORE DEL LABBRO",		
	Muscolo_DEPRESSORE_ANGOLO_BOCCA: "DEPRESSORE ANGOLO DELLA BOCCA",		
	Muscolo_ELEVATORE_ALA_NASO: "ELEVATORE ALA DEL NASO",		
	Muscolo_CORRUGATORE: "CORRUGATORE",			
	Muscolo_BUCCINATORE: "BUCCINATORE",			
	Muscolo_PLATISMA: "PLATISMA",			
	Muscolo_RISORIO: "RISORIO",			
	Muscolo_DEPRESSORE_LABBRO: "DEPRESSORE DEL LABBRO",			
	Muscolo_ORBICOLARE_BOCCA: "ORBICOLARE DELLA BOCCA",			
	Muscolo_NASALE: "NASALE",			
	Muscolo_MENTALE: "MENTALE",			
	Muscolo_MILOIOIDEO: "MILOIOIDEO",			
	Muscolo_STILOIOIDEO: "STILOIOIDEO",			
	Muscolo_DIGASTRICO: "DIGASTRICO",		
	Muscolo_STERNOCLEIDOMASTOIDEO: "STERNOCLEIDOMASTOIDEO",	
	Muscolo_STERNOIOIDEO: "STERNOIOIDEO",	
	Muscolo_OMOIOIDEO: "OMOIOIDEO",
	Muscolo_TIROIDEO: "TIROIDEO",
	Muscolo_SCALENI: "SCALENI",
	Muscolo_SPLENIO_DELLA_TESTA: "SPLENIO DELLA TESTA",
	Muscolo_ELEVATORE_DELLA_SCAPOLA: "ELEVATORE DELLA SCAPOLA",
	Muscolo_SARTORIO: "SARTORIO",
	Muscolo_QUADRICIPITE_FEMORALE: "QUADRICIPITE FEMORALE",
	Muscolo_VASTO_LATERALE: "VASTO LATERALE",
	Muscolo_VASTO_MEDIALE: "VASTO MEDIALE",
	Muscolo_RETTO: "RETTO DEL FEMORE",
	Muscolo_GRACILE: "GRACILE",
	Muscolo_ADDUTTORE_LUNGO: "ADDUTTORE LUNGO",
	Muscolo_PETTINEO: "PETTINEO",
	Muscolo_ILEO: "ILEO",
	Muscolo_GRANDE_PSOAS: "GRANDE PSOAS",
	Muscolo_BICIPITE_FEMORALE: "BICIPITE FEMORALE",
	Muscolo_SEMITENDINOSO: "SEMITENDINOSO",
	Muscolo_SEMIMEMBRANOSO: "SEMIMEMBRANOSO",
	Muscolo_GRANDE_ADDUTTORE: "GRANDE ADDUTTORE",
	Muscolo_DELTOIDE: "DELTOIDE",
	Muscolo_CORACOBRACHIALE: "CORACO-BRACHIALE",
	Muscolo_BICIPITE_BRACHIALE: "BICIPITE BRACHIALE",
	Muscolo_TRICIPITE_BRACHIALE: "TRICIPITE BRACHIALE",
	Muscolo_BRACHIALE: "BRACHIALE",
	Muscolo_ANCONEO: "ANCONEO",
	Muscolo_BRACHIORADIALE: "BRACHIORADIALE",
	Muscolo_ESTENSORE_RADIALE_LUNGO_CARPO: "ESTENSORE RADIALE LUNGO DEL CARPO",
	Muscolo_ESTENSORE_RADIALE_BREVE_CARPO: "ESTENSORE RADIALE BREVE DEL CARPO",
	Muscolo_ABDUTTORE_LUNGO_POLLICE: "ABDUTTORE LUNGO DEL POLLICE",
	Muscolo_ESTENSORE_BREVE_POLLICE: "ESTENSORE BREVE DEL POLLICE",
	Muscolo_ESTENSORE_LUNGO_POLLICE: "ESTENSORE LUNGO DEL POLLICE",
	Muscolo_ESTENSORE_COMUNE_DITA: "ESTENSORE COMUNE DELLE DITA",
	Muscolo_ESTENSORE_PROPRIO_MIGNOLO: "ESTENSORE PROPRIO DEL MIGNOLO",
	Muscolo_ESTENSORE_ULNARE_CARPO: "ESTENSORE ULNARE DEL CARPO",
	Muscolo_FLESSORE_ULNARE_CARPO: "FLESSORE ULNARE DEL CARPO",
	Muscolo_PRONATORE: "PRONATORE",
	Muscolo_FLESSORE_RADIALE_CARPO: "FLESSORE RADIALE DEL CARPO",
	Muscolo_PALMARE_LUNGO: "PALMARE LUNGO",
	Muscolo_FLESSORI_SUPERFICIALI_DITA: "FLESSORI SUPERFICIALI DELLE DITA",
	Muscolo_ABDUTTORE_BREVE_POLLICE: "ABDUTTORE BREVE DEL POLLICE",
	Muscolo_FLESSORE_BREVE_POLLICE: "FLESSORE BREVE DEL POLLICE",
	Muscolo_OPPONENTE_POLLICE: "OPPONENTE DEL POLLICE",
	Muscolo_ADDUTTORE_POLLICE: "ADDUTTORE DEL POLLICE",
	Muscolo_LOMBRICALI: "LOMBRICALI",
	Muscolo_FLESSORE_MIGNOLO_MANO: "FLESSORE DEL MIGNOLO",
	Muscolo_ABDUTTORE_MIGNOLO_MANO: "ABDUTTORE DEL MIGNOLO",
	Muscolo_PALMARE_BREVE: "PALMARE BREVE",
	Muscolo_INTEROSSEI_DORSALI_MANO: "INTEROSSEI DORSALI",	
	Muscolo_GASTROCNEMIO: "GASTROCNEMIO",
	Muscolo_TENDINE_ACHILLE: "TENDINE DI ACHILLE",
	Muscolo_SOLEO: "SOLEO",
	Muscolo_PERONEO_LUNGO: "PERONEO LUNGO",
	Muscolo_PERONEO_BREVE: "PERONEO BREVE",
	Muscolo_TIBIALE_ANTERIORE: "TIBIALE ANTERIORE",
	Muscolo_ESTENSORE_LUNGO_DITA: "ESTENSORE LUNGO DELLE DITA",
	Muscolo_ESTENSORE_LUNGO_ALLUCE: "ESTENSORE LUNGO DELL'ALLUCE",
	Muscolo_ESTENSORE_BREVE_ALLUCE: "ESTENSORE BREVE DELL'ALLUCE",
	Muscolo_ESTENSORI_BREVI_DITA: "ESTENSORI BREVI DELLE DITA",
	Muscolo_ADDUTTORE_ALLUCE: "ADDUTTORE DELL'ALLUCE",
	Muscolo_FLESSORE_BREVE_DITA: "FLESSORE BREVE DELLE DITA",
	Muscolo_FLESSORE_LUNGO_DITA: "FLESSORE LUNGO DELLE DITA",
	Muscolo_FLESSORE_LUNGO_ALLUCE: "FLESSORE LUNGO DELL'ALLUCE",
	Muscolo_ABDUTTORE_MIGNOLO_PIEDE: "ABDUTTORE DEL MIGNOLO (PIEDE)",
	Muscolo_FLESSORE_MIGNOLO_PIEDE: "FLESSORE DEL MIGNOLO",
	
	// zone anatomiche
	Zona_TESTA: "Muscoli della testa",
	Zona_ORECCHIO: "Aree dell'orecchio",
	Zona_COLLO: "Muscoli del collo",
	Zona_TORSO: "Muscoli del tronco",
	Zona_ARTO_SUPERIORE: "Muscoli dell'arto superiore",
	Zona_ARTO_INFERIORE: "Muscoli dell'arto inferiore",

	// aree orecchio
	Muscolo_TUBERCOLO_DI_DARWIN: "TUBERCOLO DI DARWIN",
	Muscolo_CODA_DELL_ELICE: "CODA DELL'ELICE",
	Muscolo_CORPO_DELL_ELICE: "CORPO DELL'ELICE",
	Muscolo_BRANCA_MONTANTE_DELL_ELICE: "BRANCA MONTANTE DELL'ELICE",
	Muscolo_GINOCCHIO_DELL_ELICE: "GINOCCHIO DELL'ELICE",
	Muscolo_RADICE_DELL_ELICE: "RADICE DELL'ELICE",
	Muscolo_DOCCIA_SCAFOIDE: "DOCCIA SCAFOIDE",
	Muscolo_CRESTA_DELL_AURICOLA: "CRESTA DELL'AURICOLA",
	Muscolo_FOSSETTA_TRIANGOLARE: "FOSSETTA TRIANGOLARE",
	Muscolo_EMICONCA_SUPERIORE: "EMICONCA SUPERIORE",
	Muscolo_EMICONCA_INFERIORE: "EMICONCA INFERIORE",
	Muscolo_TRAGO: "TRAGO",
	Muscolo_ANTITRAGO: "ANTITRAGO",
	Muscolo_ANGOLO_ELICO_LOBULARE: "ANGOLO ELICO-LOBULARE",
	Muscolo_LOBO: "LOBO",
	Muscolo_SOLCO_PRELOBULARE: "SOLCO PRE-LOBULARE",
	Muscolo_SOLCO_SOTTO_ANTITRAGALE: "SOLCO SOTTO-ANTITRAGALE",
	Muscolo_FORO_ACUSTICO_ESTERNO: "FORO ACUSTICO ESTERNO",
	Muscolo_EMINENZA_LOBOLARE: "EMINENZA LOBULARE",
	Muscolo_FOSSA_RETROLOBULARE: "FOSSA RETRO-LOBULARE",
	Muscolo_CONVESSITA_EMICONCA_INFERIORE: "CONVESSITA' EMICONCA INFERIORE",
	Muscolo_CONVESSITA_EMICONCA_SUPERIORE: "CONVESSITA' EMICONCA SUPERIORE",
	Muscolo_EMINENZA_ELICALE: "EMINENZA ELICALE",
	Muscolo_CONVESSITA_FOSSETTA_TRIANGOLARE: "CONVESSITA' FOSSA TRIANGOLARE",
	Muscolo_DOCCIATURA_ANTELICALE_POSTERIORE: "DOCCIATURA ANTELICALE POSTERIORE",
	Muscolo_EMINENZA_CENTRALE: "EMINENZA CENTRALE",
	Muscolo_FOSSETTA_CENTRALE_POSTERIORE: "FOSSETTA CENTRALE POSTERIORE",
	Muscolo_ANTELICE: "ANTELICE",
	Muscolo_RAMO_INFERIORE: "RAMO INFERIORE",
	Muscolo_RAMO_SUPERIORE: "RAMO SUPERIORE",
		
}
	